.github/workflows/pull-request-auto-assign.yaml

Auto Assign Team Members to Pull Request

---

.github/workflows/ci-api.yaml

API CI Action

---

.github/workflows/snyk.yaml

Snyk scanning

---

src/backend/server.js

api cleanup

---

.gitignore
src/backend/.dockerignore
src/backend/package-lock.json
src/backend/package.json
src/backend/server.js

Code Coverage for API

---

src/backend/package.json

adding nyc to package.json

---

.github/workflows/code-coverage.yaml
src/backend/package.json

Create Github Action to Generate Coverage JSON output file

---

openshift/templates/api/api-dc-template.yaml

Removing Underscores

---

.github/workflows/code-coverage.yaml

 rename code-coverage action

---

.github/workflows/build-deploy-api.yaml

Getting Previous DC Name for Cleanup

---

.github/workflows/build-deploy-api.yaml

blocking out pt.1 of cleanup

---

.github/workflows/build-deploy-api.yaml

process and apply service and route templates

---

openshift/templates/api/api-route.yaml
openshift/templates/api/api-service.yaml

creating template objects

---

.github/workflows/build-deploy-api.yaml

adding new upload file

---

.github/workflows/build-deploy-api.yaml

troubleshooting

---

.github/workflows/build-deploy-api.yaml

adding to awk

---

.github/workflows/build-deploy-api.yaml

adding final cleanup stages

---

.github/workflows/build-deploy-api.yaml

adding repo checkout

---

.github/helpers/deploy.sh
.github/workflows/build-deploy-api.yaml

refactoring the dev workflow

---

.github/workflows/build-deploy-api.yaml

troubleshooting array

---

.github/helpers/deploy.sh
.github/workflows/build-deploy-api.yaml

array in deploy script

---

.github/workflows/build-deploy-api.yaml

adding deploy to test

---

.github/workflows/build-deploy-api.yaml

test deploy troubleshooting

---

src/frontend/Dockerfile

adding dockerfile

---

docker-compose.yaml
src/frontend/Dockerfile

docker compose changes

---

.github/workflows/build-deploy-app.yaml

github action for build tag push image

---

.github/workflows/build-deploy-app.yaml

typo in base url

---

src/frontend/Dockerfile
src/frontend/nginx.conf

changes to dockerfile

---

src/frontend/Dockerfile

changing nginx image

---

src/frontend/Dockerfile
src/frontend/nginx.conf

re-adding nginx conf

---

docker-compose.yaml
src/frontend/Dockerfile

changes to docker

---

.github/helpers/deploy.sh
.github/workflows/build-deploy-api.yaml
.github/workflows/build-deploy-app.yaml

adding component specific directory to deploy script

---

.github/helpers/deploy.sh
.github/workflows/build-deploy-api.yaml
.github/workflows/build-deploy-app.yaml

adding less specific env vars

---

.github/workflows/build-deploy-app.yaml

remove url

---

openshift/templates/api/api-service-template.yaml
openshift/templates/app/app-service-template.yaml

updating ports on service templates

---

.github/workflows/build-deploy-app.yaml
openshift/templates/app/app-route-template.yaml

App GitHub action

---

.github/workflows/build-deploy-api.yaml

adding troubleshooting check

---

.github/workflows/build-deploy-api.yaml

Graceful exit

---

openshift/templates/app/app-route-template.yaml
openshift/templates/app/app-service-template.yaml

re-doing service and route templates

---

.github/workflows/build-deploy-api.yaml
.github/workflows/build-deploy-app.yaml
openshift/templates/app/app-dc-template.yaml

adding labels to oc get dc command

---

.github/workflows/build-deploy-api.yaml

adding healthcheck and cleanup for test

---

.github/workflows/build-deploy-api.yaml

App service route

---

.github/workflows/build-deploy-app.yaml

adding TEST tag, deploy, health and cleanup

---

.github/workflows/build-deploy-app.yaml

adding DEV cleanup

---

src/backend/server.js

did not version the api-docs

---

.github/helpers/increment-tag.sh

Increment version script

---

.github/helpers/increment-tag.sh

turning off echo statements

---

.github/workflows/build-deploy-api.yaml

adding increment and tag version

---

.github/workflows/build-deploy-api.yaml

typo file name

---

.github/workflows/build-deploy-api.yaml

missing argument

---

.github/helpers/increment-tag.sh

command substitution error

---

.github/helpers/increment-tag.sh

removing quotes

---

.github/helpers/increment-tag.sh

command subsitution

---

.github/helpers/increment-tag.sh

trying to restore functionality"

---

.github/helpers/increment-tag.sh

adding todo

---

.github/workflows/build-deploy-api.yaml

command substitution update

---

.github/workflows/build-deploy-api.yaml

checking for tags after checkout

---

.github/workflows/build-deploy-api.yaml

adding find tag github action

---

.github/helpers/increment-tag.sh

changing script output

---

.github/helpers/increment-tag.sh
.github/workflows/build-deploy-api.yaml

adding steps for new tag identification

---

.github/workflows/build-deploy-api.yaml

updating find tag

---

.github/workflows/build-deploy-api.yaml

adding PROD deploy with version tag

---

.github/helpers/increment-tag.sh

generating commit

---

.github/workflows/api-docker.yaml
.github/workflows/code-coverage.yaml
.github/workflows/codeql.yml
.github/workflows/pull-request-auto-assign.yaml
.github/workflows/snyk.yaml

turning off actions

---

.github/workflows/build-deploy-api.yaml

turning unshallow off

---

.github/workflows/build-deploy-api.yaml

removing tag action for git describe inline

---

.github/workflows/build-deploy-api.yaml

adding fetch

---

.github/workflows/build-deploy-api.yaml

altering fetch

---

.github/workflows/build-deploy-api.yaml

modifying checkout

---

.github/workflows/build-deploy-api.yaml

adding new tag steps

---

.github/workflows/build-deploy-api.yaml

adding image tag to env

---

openshift/templates/api/api-dc-template-prod.yaml

removing image tag from all fields except image ref

---

.github/workflows/build-deploy-api.yaml

adding dir env var

---

.github/workflows/build-deploy-api.yaml

renaming env vars

---

.github/helpers/deploy-prod.sh
.github/workflows/build-deploy-api.yaml

adding updated prod deploy script for only dc

---

.github/workflows/build-deploy-api.yaml

adding urls to prod environment

---

.github/workflows/build-deploy-api.yaml

trimming URL to health check stage only

---

.github/workflows/build-deploy-api.yaml

refactoring api environment

---

.github/workflows/build-deploy-app.yaml

forgot one environment update

---

.github/workflows/owasp-zap.yaml

UTOPIA-30: OWASP Scan for Web App

UTOPIA-30: OWASP Scan for Web App

---

.github/workflows/codeql.yml
.github/workflows/snyk.yaml

UTOPIA-38/39: Snyk and CodeQL Scan Cron Job Schedule

---

.github/labeler.yml

Auto Labeler Config Comment

---

.github/workflows/build-deploy-api.yaml
.github/workflows/build-deploy-app.yaml

UTOPIA-36: Git Environments - Debug cleanup

UTOPIA-36: Git Environments - Debug cleanup

---

.github/workflows/zap-frontend-scan.yaml

Zap Frontend Action typo

---

.github/workflows/app-docker.yaml

UTOPIA-55: Git Action Build WebApp Docker Container on PR Open

UTOPIA-55: Git Action Build WebApp Docker Container on PR Open

---

.github/dependabot.yaml

UTOPIA-60: Add Dependabot YAML config to repo

UTOPIA-60: Add Dependabot YAML config to repo

---

src/frontend/dpia-webapp/index.html

UTOPIA-138: Adding snowplow

---

src/frontend/dpia-webapp/Dockerfile

cleaning up dockerfile

---

Makefile

UTOPIA-63: Project Makefile

---

.github/workflows/build-deploy-api.yaml
openshift/templates/network-policies/allow-from-openshift-ingress.yaml
openshift/templates/network-policies/any-to-any.yaml
openshift/templates/network-policies/any-to-external.yaml
src/backend/server.js

trying to redeploy api without error

---

src/backend/Dockerfile

changing node image for api build

---

src/backend/Dockerfile

updating docker image

---

src/backend/Dockerfile

rolling node back to 18.5

---

src/backend/server.js

alan sleuthing

---

src/backend/server.js

modiying app.listen()

---

src/backend/server.js

adding localhost as ip

---

.gitignore
src/frontend/dpia-webapp/Dockerfile
src/frontend/dpia-webapp/nginx.conf
src/frontend/dpia-webapp/package-lock.json
src/frontend/dpia-webapp/package.json

Workstation Setup Diff

---

openshift/templates/app/app-dc-template.yaml
openshift/templates/app/app-route-template.yaml
openshift/templates/app/app-service-template.yaml

removing image tag from name of service/route

---

.github/workflows/build-deploy-app.yaml

Code Cleanup

---

openshift/templates/app/app-dc-template.yaml

adding hash label to container/pod

---

openshift/templates/app/app-dc-template.yaml

rewind dc changes

---

.github/helpers/cleanup.sh
.github/workflows/build-deploy-app.yaml

altering cleanup script and cleanup job/tasks

---

.github/helpers/cleanup-pods.sh
.github/helpers/cleanup-rc.sh
.github/helpers/cleanup.sh
.github/workflows/build-deploy-app.yaml

Test Environment Enable

---

.github/workflows/build-deploy-app.yaml

enabled deploy and healthcheck in TEST

---

.github/helpers/tag-imagestream-release.sh
.github/helpers/tag-imagestream.sh
.github/workflows/build-deploy-app.yaml

cleaned up tagging process, removing tag prod helper script

---

.github/workflows/build-deploy-app.yaml

removing env comments

---

.github/workflows/build-deploy-app.yaml

env var string typo

---

.github/workflows/build-deploy-app.yaml

indentation error

---

.github/workflows/build-deploy-app.yaml

error with docker push

---

.github/workflows/build-deploy-app.yaml

fixing dc imagetag ref

---

.github/workflows/build-deploy-app.yaml

full prod deploy unlocked

---

.github/workflows/build-deploy-app.yaml

typo in environment url field

---

.github/workflows/build-deploy-api.yaml

Cleaning up DEV API Jobs

---

openshift/templates/api/api-route-template.yaml
openshift/templates/api/api-service-template.yaml
openshift/templates/app/app-route-template.yaml

Cleaning up API Templates

---

.github/workflows/build-deploy-api.yaml

turning on TEST jobs

---

.github/workflows/build-deploy-api.yaml

removing old json file

---

openshift/templates/api/api-dc-template.yaml

changing api logo

---

.github/workflows/build-deploy-api.yaml
.github/workflows/build-deploy-app.yaml

turning on api prod deploy

---

.github/workflows/build-deploy-api.yaml

remove prod shell script

---

src/frontend/dpia-webapp/Dockerfile

base image

---

src/frontend/dpia-webapp/Dockerfile

adding nginx user

---

docker-entrypoint.sh
src/frontend/dpia-webapp/Dockerfile
src/frontend/dpia-webapp/unitd-conf.json

Docker unit

---

src/frontend/dpia-webapp/Dockerfile

node 16 image build

---

package-lock.json
src/frontend/dpia-webapp/app/public/404/index.nj
src/frontend/dpia-webapp/config.json
src/frontend/dpia-webapp/main.js
src/frontend/dpia-webapp/route.json

- Adds 404 page and creates the necessary redirect.
Typed in URLs that were not defined and correctly saw the 404 page.

Brandon 404 page

---

.github/workflows/pull-request-auto-assign.yaml

UTOPIA-21 - onboarding EY team into github repo as collaborators and PR reviewers
Pull request open

UTOPIA-21: Onboard EY Team into Git Repo Team

---

.github/PULL_REQUEST_TEMPLATE.md

UTOPIA-246: Updated Pull Request Template including Development Guidelines/Working Agreement
Updating pull request template to include updated team working/development agreements
None.

UTOPIA-246: Updated Pull Request Template including Development Guidelines/Working Agreement

---

.github/workflows/pull-request-auto-assign.yaml

UTOPIA-247: Adding Brandon Bouchard to Github Contributors List
None.

UTOPIA-247: Adding Brandon Bouchard to Github Contributors List

---

README.md

Docker compose instructions changed to reflect renaming of containers.
- Updates README.md to refect changes to docker-compose.yml
- dpia-webapp -> dpia-frontend
N/a

Update README.md for docker-compose instructions

---

src/frontend/index.html

Adding bootstrap from CDN and not npm

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/App.tsx
src/frontend/src/sass/_buttons.scss
src/frontend/src/sass/_default.scss
src/frontend/src/sass/_footer.scss
src/frontend/src/sass/_header.scss
src/frontend/src/sass/_variables.scss
src/frontend/src/sass/common.scss

- Creates / modifies css design tokens based on BC Gov style guidelines
Created test elements in App.tsx and applied styles using new BC Gov styles

UTOPIA-252: Add BC Gov CSS Styles

---

docker-compose.yaml

- Reverts the dpia-frontend container name back to dpia-webapp to fix github build-deploy-app action
N/a. Won't be able to test until after this PR merge.

UTOPIA-221: Deploy React JS Frontend to Openshift via Github Actions

---

Makefile
README.md
docker-compose.local.yaml
docker-compose.yaml
openshift/templates/api/api-dc-template.yaml
openshift/templates/api/api-route-template.yaml
src/backend/.docker/Dockerfile
src/backend/.docker/Dockerfile.local

- Fixing docker issues
- Deployment is currently failing possibly due to incorrect endpoint configuration - fixed it

Utopia 214: Deploy NestJS to Openshift via Github Actions

---

src/frontend/src/pages/LandingPage.tsx

- Adds link to more info about PIAs on the landing page
Spun up frontend container and clicked the link. Redirected as expected.

UTOPIA-187: See links to existing Privacy Information 

---

src/frontend/src/pages/LandingPage.tsx

- Attaches mailto link to 'Contact' button on landing page
Ran application, clicked 'Contact' button, and then the mail client opened.

UTOPIA-193: Who is involved in the DPIA

---

.github/workflows/build-deploy-api.yaml
Makefile
openshift/templates/api/api-dc-template.yaml
openshift/templates/api/api-route-template.yaml
src/backend/src/main.ts

Backend pipeline not building: attempt to fix it
[UTOPIA-214](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-214) (PR-2)
- added env to build pipeline

UTOPIA-214: Deploy NestJS to Openshift via Github Actions (PR-2)

---

src/frontend/src/pages/LandingPage.tsx
src/frontend/src/sass/LandingPage.scss

- Adds callout component to landing page
- Adjusts existing styling on landing page to accommodate the callout component
Ran `npm run dev` and checked layout.

UTOPIA-269: Add Callout to Landing Page

---

src/backend/.docker/Dockerfile

This is second attempt to fix backend pipeline issues - providing user access based on debugging from pod logs
- updated user permissions for openshift

UTOPIA-214: Deploy NestJS to Openshift via Github Actions (PR-attempt-3;) 

---

src/backend/.docker/Dockerfile

Another attempt to fix the pipeline issues 🤞 
- provided user with npm logs access

UTOPIA-214: Deploy NestJS to Openshift via Github Actions (PR#4)

---

src/frontend/src/components/public/ProgressBar/Stage.tsx
src/frontend/src/components/public/ProgressBar/Stages.tsx
src/frontend/src/components/public/ProgressBar/interfaces.ts

This PR does not include the styling of the components.
- Creates Stage component
- Creates Stages component
- Creates StageProps interface
- Create StagesProps interface
Created a test array of properties to map through to render the Stage and Stages components on the Landing Page. The components rendered as expected.

UTOPIA-301: Create components for use within Progress Bar

---

Makefile
docker-compose.local.yaml
src/backend/.config/.env.local

- Docker configuration for Postgres to work locally (Local environment)
- Tried running the environment database locally multiple times

Local env - Postgres configuration

---

src/frontend/package.json
src/frontend/src/App.tsx
src/frontend/tsconfig.json

the vite build command failed when build docker image, fix it
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code DOES NOT include the importing of new dependencies into the DPIA ecosystem
- [ x] N/A
- [x ] N/A

fix vite build to exclude cypress files

---

src/frontend/src/main.tsx

fix route for ppq landing page
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My code DOES NOT include the importing of new dependencies into the DPIA ecosystem
- [x ] I have performed a self-review of my own code
- [ x] N/A

fix route for ppq landing page

---

src/backend/.docker/Dockerfile

Add CURL to API Container

---

src/backend/.docker/Dockerfile

API Container APK instead of apt-get

---

openshift/templates/api/api-dc-template.yaml

Updating Paramter in API kubernetes template

---

openshift/templates/api/api-route-template.yaml
openshift/templates/api/api-service-template.yaml

Adding Database Service to templates

---

openshift/templates/app/app-dc-template.yaml
src/frontend/Dockerfile

Adding Database Service to APP Template

---

src/frontend/package-lock.json
src/frontend/package.json

Removes esbuild-arm64 dependency from package.json and package-lock.json

---

.github/helpers/deploy.sh
.github/workflows/build-deploy-api.yaml
openshift/templates/api/api-dc-template.yaml
openshift/templates/api/api-route-template.yaml
openshift/templates/api/api-service-template.yaml

Adding POSTGRES Connection Env Variables as Secret

---

src/frontend/Dockerfile

Creating diff to re-fire FRESH pipeline 

---

src/backend/package.json

- temp-remove-migrations-on-startup to make container healthy

temp-remove-migrations-on-startup

---

src/backend/package.json

This reverts commit 0d62ae762590fadd274364b71e7a3cc815448532.

Revert "temp-remove-migrations-on-startup"

---

src/backend/package.json
src/backend/src/config/config.service.ts

- auto run migrations on non local envs

auto run migrations on non local envs

---

openshift/templates/api/api-dc-template.yaml

Update Readiness and Liveness Probes on API Deployment Config

---

src/frontend/src/components/public/PPQConnect/index.tsx
src/frontend/src/sass/Card.scss
src/frontend/src/sass/PPQConnect.scss
src/frontend/src/sass/_buttons.scss
src/frontend/src/sass/common.scss
src/frontend/src/sass/index.scss

- Creates PPQConnect molecular component
- Adds PPQConnect styling
- Tweaks some existing styling
Rendered the component on the LandingPage to assess accuracy against provided designs.

Utopia 234: List of MPO

---

src/backend/.docker/postgres/init.sql

UTOPIA-317: Creating Init Script for Postgres Container

---

openshift/templates/api/api-route-template.yaml

Changing Openshift API route to serve at api-docs

---

src/frontend/src/components/public/PPQConnect/index.tsx
src/frontend/src/components/public/PPQResults/index.tsx
src/frontend/src/pages/LandingPage.tsx
src/frontend/src/pages/PPQConnectPage.tsx
src/frontend/src/pages/PPQFormPage.tsx
src/frontend/src/pages/PPQResultsPage.tsx
src/frontend/src/routes/router.tsx
src/frontend/src/sass/PPQConnect.scss
src/frontend/src/sass/PPQResults.scss
src/frontend/src/sass/ProgressBar.scss

This implementation **needs a major refactor** starting at the beginning of the next sprint! The purpose is to allow work to be shown for the sprint demo and then to realize a proper solution for early next sprint.
- Creates pages to show the results and connect with mpo components for the sprint demo

Create pages for the results and connect components

---

src/frontend/src/components/public/PPQConnect/index.tsx

Puts window.open in the pdf button inside an anonymous function.

---

src/frontend/src/pages/PPQFormPage.tsx

- Groups PPQ form radio buttons with 'name' property
- Provides defaultChecked to radio button groups
Spun up frontend container and tested correct UI behaviour on radio buttons.

UTOPIA-347: Fix PPQ Form Radio Buttons

---

src/frontend/src/components/common/Card/index.tsx
src/frontend/src/components/public/PPQResults/test-ppq-results.ts
src/frontend/src/sass/PPQConnect.scss
src/frontend/src/sass/PPQResults.scss

- Center aligns Cards inside of the Results component

UTOPIA-350: Adjust Results component Card spacing to reflect design changes

---

src/frontend/.eslintrc.js

- disable auto add space in jsx child element
- https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-child-element-spacing.md

diable auto add space eslint rule

---

src/backend/src/app.config.ts

-only enable cors for local development
- [ x] New feature (non-breaking change which adds functionality)
- [x ] My code DOES NOT include the importing of new dependencies into the DPIA ecosystem
- [x ] N/A
- [x ] I have performed a self-review of my own code

307-only enable cors for localhost

---

openshift/templates/app/app-route-template.yaml

UTOPIA-368: Single Base URL Route Creation (Frontend)

---

openshift/templates/api/api-route-template.yaml

UTOPIA-369: Single Base URL Route Creation (API)

---

src/backend/.docker/Dockerfile

- After pod failure, providing puppeteer access to earlier 1001 OpenShift user

updating user to default OS user as previously working

---

src/frontend/src/components/public/PPQConnect/index.tsx

- currently click done button will go to landing page, after change will go to home page(ppq )
- update some styles, use   "&lsquo;"can be escaped single left quoto

UTOPIA-375:update ppq connect page done button behavior

---

src/frontend/src/components/common/Navbar/navPages.ts

- remove home button from nav bar component

UTOPIA-374:remove home button from nav bar

---

src/frontend/src/utils/file-download.util.ts
src/frontend/src/utils/http-request.util.ts

- Fixed Vite build failure
Ran local build

vite build fix

---

src/frontend/src/components/public/PPQConnect/index.tsx
src/frontend/src/sass/PPQConnect.scss

- Link for MPO contacts now opens a new browser tab on click
- Space has been added between sentences on the first line after the '1. Find you MPO' heading
- Spun up the application and clicked the link to MPO list to confirm new page open
- Visually assessed spacing change on the line with the link to MPO list

UTOPIA-234: List of MPOs -- Changes to meet AC

---

src/frontend/src/components/common/Navbar/_navbar.scss

- Added fix to md editor overlaying the nav

[UTOPIA-378] [Frontend] Added fix to md editor overlaying the nav

---

src/frontend/src/constant/constant.ts

- Appends missing final sentence to the tooltip text for the 'sensitive personal information' tooltip
N/A

UTOPIA-263: Hints & Definitions

---

.github/workflows/api-unit-test.yaml

UTOPIA-385: API Automated Unit Tests on Pull Request

UTOPIA-385: API Automated Unit Tests on Pull Request

---

src/frontend/src/components/common/Checkbox/_checkbox.scss
src/frontend/src/components/common/Checkbox/index.tsx
src/frontend/src/pages/PPQFormPage/PPQFormPage.scss
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx

- Clicking input labels also selects respective input element
- Radio buttons now have a default selection
- Radio button alignment and spacing corrected to mirror Figma designs
Spun up application and checked for visual changes and tested selecting on labels instead of radio or checkbox itself.

UTOPIA-392, 393, and 394

---

src/frontend/src/components/common/Checkbox/_checkbox.scss
src/frontend/src/pages/PPQFormPage/PPQFormPage.scss
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx
src/frontend/src/sass/_variables.scss

**!!PLEASE NOTE!!**
Some of these changes won't look entirely correct until combined with my previously submitted PR!
- Adds new questions from designs
- Changes form question order
- Adjusts form layout to match designs
- Creates new scss variable 'text-gray' which is used for addtional question detail text
- Headings and subheading are now correct in size and colour

UTOPIA-388, 389, 390, & 391: Form Question Order, Form Layout, Form Fonts

---

.github/workflows/api-lint.yaml
.github/workflows/api-unit-test.yaml
.github/workflows/app-lint.yaml

UTOPIA-385: API Automated Unit Tests on PR

UTOPIA-385: API Automated Unit Tests on PR

---

.github/workflows/api-lint.yaml

Fixing Broken Lint Action

---

.github/workflows/app-lint.yaml

Fixing Broken App Lint

---

.github/workflows/api-lint.yaml
.github/workflows/app-lint.yaml

Fixing Broken Lint Actions

---

openshift/templates/api/api-dc-template.yaml

UPTOPIA-404: Implementing API Environment Variable for Keycloak Auth in DEV

UPTOPIA-404: Implementing API Environment Variable for Keycloak Auth in DEV

---

openshift/templates/api/api-dc-template.yaml

UTOPIA-404: Implementing API Environment Variable for Keycloak Auth in DEV

UTOPIA-404: Implementing API Environment Variable for Keycloak Auth in DEV

---

src/frontend/src/components/common/CustomInputDate/custom_input_date.scss
src/frontend/src/components/common/CustomInputDate/index.tsx
src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/constant/constant.ts
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx
src/frontend/src/pages/PPQFormPage/messages.ts
src/frontend/src/sass/common.scss
src/frontend/src/utils/helper.util.ts

1. This PR includes the following Bug Fixes
- Name should be a text field instead of a dropdown
- "Personal Information" Link missing
- Dropdown not by the design AND incorrect placeholder value (capital MM instead of lowercase mm)
- Acceptance Criteria 6 says - "Does your initiative involve any of the following?" question only appears if the user has selected "Yes" to "Is PI involved in your initiative";; AC not met; "Does your initiative involve..." question appears regardless
- Acceptance Criteria 7 says - Date picker to enter start date only appears if user answers "yes" to "Do you have a proposed start date?";;; AC not met; Seeing "Proposed start date" without "Yes" selected
2. This PR also try to component-ize the reusables code
3. This PR removes the code not relevant for this …

[UTOPIA-398] [Frontend] Form Bug Fixes

---

src/frontend/src/components/common/Spinner/Spinner.scss
src/frontend/src/components/common/Spinner/index.tsx
src/frontend/src/components/common/Spinner/interfaces.ts
src/frontend/src/components/public/PPQConnect/index.tsx
src/frontend/src/sass/common.scss

- Added Spinner common component [No external library used]
- Integrated spinner reflect pdf download loading 
- Refactor error messages via pdf download view via the Alert component
Tested with both success and failure scenarios. Screenshots attached for loading state and error state.
--- LOADING STATE ---
--- ERROR STATE ---

[Utopia 409] [Common Component] Added Spinner common component + PDF download integration

---

.github/workflows/api-lint.yaml
.github/workflows/api-unit-test.yaml
.github/workflows/app-lint.yaml

Troubleshooting pipeline bug

---

.github/workflows/api-lint.yaml
.github/workflows/api-unit-test.yaml
.github/workflows/app-lint.yaml

Troubleshooting Pipeline Issues

---

src/backend/src/modules/ppq/templates/ppq-result.pug

- Fixed PDF spacing issue when content goes beyond one page

[UTOPIA-414] fixed pdf spacing issue for new pages

---

src/frontend/src/components/common/Navbar/index.tsx

UTOPIA-361-fix navbar styling

---

src/frontend/src/App.tsx
src/frontend/src/components/public/PPQConnect/index.tsx
src/frontend/src/components/public/PPQResults/PPQResults.scss
src/frontend/src/components/public/PPQResults/index.tsx
src/frontend/src/pages/PPQConnectPage.tsx
src/frontend/src/pages/PPQFormPage/PPQFormPage.scss
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx
src/frontend/src/pages/PPQPage/PPQPage.scss
src/frontend/src/pages/PPQPage/PPQPage.tsx
src/frontend/src/sass/App.scss

- Adds grey border to first two ppq pages
- Removes Navbar from initial landing page
- Adjusts layout of first ppq page

UTOPIA-349 & 412: Styling Fixes

---

.github/workflows/build-deploy-api.yaml
.github/workflows/build-deploy-app.yaml

Updating Github Environments URLs

UTOPIA-411: Github Environment URL Update for API and APP

---

adr-log/adr-template.md
adr-log/puppeteer-for-pdf.md

- Includes documentation for using Puppeteer for PDF
- Include ADR template
N/A

[Utopia 443] [Documentation] Puppeteer for PDF

---

.github/helpers/deploy.sh
.github/workflows/build-deploy-api.yaml
openshift/templates/api/api-dc-template.yaml
openshift/templates/api/api-route-template.yaml
openshift/templates/api/api-service-template.yaml

UTOPIA-442: Add Vault Annotations to API Deplyoment Config for Postgres Variables

UTOPIA-442+451: API Template and Github Actions changes for Vault POSTGRES Variables

---

openshift/templates/app/app-dc-template.yaml

UTOPIA-457: Failed Frontend Deployment Due to Vault Secrets

UTOPIA-457: Failed Frontend Deployment Due to Vault Secrets

---

.github/PULL_REQUEST_TEMPLATE.md

UTOPIA-456: PR Definition of Done: Change img url from relative to absolute path

---

.codeclimate.yaml

UTOPIA-335: Baseline Configuration for Code Climate for Pull Request

UTOPIA-335: Baseline Configuration for Code Climate for Pull Request

---

src/frontend/src/components/public/PPQConnect/PPQConnect.scss
src/frontend/src/components/public/PPQConnect/index.tsx
src/frontend/src/components/public/PPQConnect/messages.ts
src/frontend/src/pages/PPQFormPage/PPQFormPage.scss
src/frontend/src/sass/_default.scss

- Updates copy and layout of PPQ Connect component
Spun up local container and verified visual changes

UTOPIA-428: Update Copy on the PPQ Connect Page

---

openshift/templates/api/api-dc-template.yaml

Rolling Back Vault Changes to Unblock Devs

---

openshift/templates/api/api-dc-template.yaml

Typo - False Positive Pipeline Failure

---

openshift/templates/api/api-dc-template.yaml

Key Value Pair Error on Deployment Config

---

src/backend/src/common/constants/delegated-review-types.constant.ts
src/backend/src/common/entities/base.entity.ts
src/backend/src/common/swagger.ts
src/backend/src/migrations/1668449965015-clear-ppq-table-2.ts
src/backend/src/migrations/1668456855823-ppq-add-user-info.ts
src/backend/src/modules/auth/auth.module.ts
src/backend/src/modules/auth/auth.service.ts
src/backend/src/modules/auth/keycloak-user.model.ts
src/backend/src/modules/ppq/entities/ppq.entity.ts
src/backend/src/modules/ppq/ppq.controller.spec.ts
src/backend/src/modules/ppq/ppq.controller.ts
src/backend/src/modules/ppq/ppq.module.ts
src/backend/src/modules/ppq/ppq.service.spec.ts
src/backend/src/modules/ppq/ppq.service.ts
src/backend/src/modules/ppq/templates/ppq-result.pug

- PDF changes based on new designs
- IDIR entity updates and Migrations to capture createdBy<...> fields on PPQ post submission
```
@Column({ name: 'created_by_guid' })
createdByGuid: string;
@Column({ name: 'created_by_username' })
createdByUsername: string;
@Column({ name: 'created_by_display_name' })
createdByDisplayName: string;
@Column({ name: 'created_by_email' })
createdByEmail: string;
```
- 
- Tested by submitting multiple PPQ with varied data and downloading pdf validating the results.
- Ensure Name and email are stored and shown correctly.

[UTOPIA-429] updated pdf implementation + IDIR user info changes

---

src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx
src/frontend/src/utils/file-download.util.ts
src/frontend/src/utils/http-request.util.ts

- Added Authentication Header to PPQ endpoints
Tested by saving a form and generating pdf

[UTOPIA-464] [Frontend] added authentication header to PPQ endpoints

---

src/backend/src/common/decorators/token.decorator.ts
src/backend/src/modules/ppq/ppq.controller.ts
src/backend/src/modules/ppq/ppq.service.ts

- Code Refactor to reuse fetching access token via decorators
PPQ Form submission and download continues to work as expected

[UTOPIA-463] [API] [code reusability refactor] access token fetch via decorators

---

src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx
src/frontend/src/ts/interfaces/ppq-form.interface.ts

- Adds necessary types to ppq form states: piaType & delegatedReviewType

UTOPIA-430: Type Fixes for Build in GitHub Action

---

src/frontend/src/pages/PPQConnectPage.tsx
src/frontend/src/pages/PPQResultsPage.tsx

- Removes the progress bar components from the results page

UTOPIA-467: Remove remaining Progress Bars

---

src/frontend/src/components/public/PPQConnect/PPQConnect.scss
src/frontend/src/pages/PPQConnectPage.tsx
src/frontend/src/pages/PPQFormPage/PPQFormPage.scss
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx

- Fixes layout issues created by the removal of the progress bar
Spun up a local instance of the app and visually confirmed changes.

UTOPIA-467: Fixes layout issues created by the removal of the progress bar.

---

.github/workflows/pull-request-docker-build-api.yaml

UTOPIA-468: Continuous Integration - Pull Request Docker Build API Image

UTOPIA-468: Continuous Integration - Pull Request Docker Build API Image

---

.github/workflows/pull-request-docker-build-app.yaml

UTOPIA-469: Continuous Integration - Pull Request Docker Build App Image

UTOPIA-469: Continuous Integration - Pull Request Docker Build App Image

---

src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx
src/frontend/src/utils/http-request.util.ts

- Bug fix - missing Bearer token
- Proper error logs
Form submission and pdf download happening as expected

Utopia 464 Bug fix - Token not working

---

.github/workflows/pull-request-docker-build-api.yaml

UTOPIA-468: Updating Git Action Event

---

src/backend/src/modules/ppq/templates/ppq-result.pug

- Title was renamed, but was not reflected on the template. Updated here
Title is showing up in the pdf

[UTOPIA-429] [Bug fix]: missing title in pdf

---

.github/workflows/pull-request-docker-build-api.yaml
.github/workflows/pull-request-docker-build-app.yaml

UTOPIA-468/469: CI Docker Build

---

.github/workflows/dev-build-tag-push-api.yaml
.github/workflows/dev-build-tag-push-app.yaml
openshift/templates/api/api-dc-template.yaml
openshift/templates/api/api-test-dc-template.yaml
openshift/templates/api/api-test-route.yaml
openshift/templates/api/api-test-service.yaml
openshift/templates/app/app-service-template.yaml
openshift/templates/app/app-test-dc-template.yaml
openshift/templates/app/app-test-route.yaml
openshift/templates/app/app-test-service.yaml

UTOPIA-470/471: Create Secondary Test API/APP Pipeline into DEV

---

.github/workflows/dev-build-tag-push-app.yaml

Typo In Action Name

---

.github/workflows/dev-build-tag-push-api.yaml
.github/workflows/dev-build-tag-push-app.yaml

UTOPIA-470/471: Updating Application Name Variable for Test Pipeline

---

.github/workflows/dev-build-tag-push-api.yaml
.github/workflows/dev-build-tag-push-app.yaml

Updating Test Pipeline to Point to New Imagestream Objects

---

src/frontend/src/components/common/Checkbox/_checkbox.scss
src/frontend/src/components/common/Checkbox/index.tsx
src/frontend/src/components/common/Checkbox/interfaces.ts
src/frontend/src/constant/constant.ts
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx

- Adds link to 'Sensitive Personal Information' factor in PPQ Form question #1
- Turns on tooltip for 'Data-linking' factor in PPQ Form question #1
- Reconfigures Checkbox component to accept `isLink` and `linkURL` properties in support of an above change
- Spun up app in local container
- clicked link for 'Sensitive Personal Information', worked as intended
- hovered on 'Data-linking' tooltip, behaviour met expectation

UTOPIA-399: PPQ Questions Update - Patch #1

---

src/frontend/src/components/common/Navbar/_navbar.scss

- Active navbar links are now white instead of yellow
- Navigated to PPQ landing page, visually assessed the active nav link as white instead of yellow

UTOPIA-376: Ensure Landing page behaviour is correct - Patch #1

---

openshift/templates/api/api-test-dc-template.yaml

Removing Postgres Secrets, Turning off Vault Headers

---

.github/workflows/build-deploy-api.yaml
.github/workflows/build-deploy-app.yaml

Turn PROD Deploy off APP + API - increment tag script fatal error

---

src/frontend/src/App.tsx
src/frontend/src/components/public/PPQConnect/PPQConnect.scss
src/frontend/src/sass/_buttons.scss

- Bug Fix:: Black box around information in the Connect With PCT section when browser is set to dark mode.
- Bug Fix:: Download button is too wide.
Tested on specified test case

Utopia 490: Bug Fix: UX changes

---

src/frontend/src/components/common/CustomInputDate/custom_input_date.scss
src/frontend/src/components/common/CustomInputDate/index.tsx
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx
src/frontend/src/sass/index.scss

- Bug fix: date field in ppq form is not navigable by keyboard
- Bug fix: can't enter date by keying in date instead of selecting from the picker
- Disabled Dark mode
Date picker can be selected and entered by tab

[UTOPIA-494] [Frontend] Bug fix: date field in ppq form is not navigable by keyboard; + DISABLE Dark mode

---

openshift/templates/api/api-route-template-v2.yaml
openshift/templates/api/api-service-template-v2.yaml
openshift/templates/app/app-route-template-v2.yaml
openshift/templates/app/app-service-template-v2.yaml

UTOPIA-499: Pipeline Refactor

---

src/frontend/src/sass/_buttons.scss

- #607 fixed the secondary button, but broke the home page's primary. 
- Added a fix to both our primary and secondary buttons with default width to fit-content (Usually this is by default, and so I assumed, but since we are using display: flex, defaults got overridden.
By looking at all the buttons used in the app

[UTOPIA-490 UX-fix-2] [Frontend] added default width fit-content to buttons

---

.github/helpers/tag-imagestream.sh
.github/workflows/tag-deploy-api-test.yaml
.github/workflows/tag-deploy-app-test.yaml

UTOPIA-499: TEST Pipeline Refactor

UTOPIA-499: TEST Pipeline Refactor

---

.github/workflows/tag-deploy-api-test.yaml

UPTOPIA-499: TEST Pipeline Refactor

UPTOPIA-499: TEST Pipeline Refactor

---

.github/workflows/tag-deploy-api-prod.yaml
.github/workflows/tag-deploy-app-prod.yaml

UTOPIA-499: PROD Pipeline Refactor

UTOPIA-499: PROD Pipeline Refactor

---

.codeclimate.yaml

UTOPIA-519: Reviewing Code Climate Maintainability

UTOPIA-519: Reviewing Code Climate Maintainability

---

.github/workflows/pilot-build-tag-deploy-app.yaml
openshift/templates/app/pilot/app-dc-template.yaml
openshift/templates/app/pilot/app-route-template.yaml
openshift/templates/app/pilot/app-service-template.yaml

UTOPIA-471: Webapp pilot pipeline

UTOPIA-471: Pilot Pipeline for WebApp

---

.github/workflows/pilot-build-tag-deploy-api.yaml
openshift/templates/api/pilot/api-dc-template.yaml
openshift/templates/api/pilot/api-route-template.yaml
openshift/templates/api/pilot/api-service-template.yaml

UTOPIA-470: Pilot Pipeline for API

UTOPIA-470: Pilot Pipeline for API

---

.github/workflows/pilot-build-tag-deploy-api.yaml
.github/workflows/pilot-build-tag-deploy-app.yaml

Typos in Git Actions

---

.github/workflows/pilot-build-tag-deploy-api.yaml

UTOPIA-470: Pilot API Pipeline

UTOPIA-470: Pilot API Pipeline

---

.github/workflows/pilot-build-tag-deploy-app.yaml

UTOPIA-471: WebApp Pilot Pipeline

UTOPIA-471: WebApp Pilot Pipeline

---

src/backend/src/app.module.ts
src/backend/src/common/swagger.ts
src/backend/src/modules/pia-intake/dto/create-pia-intake.dto.ts
src/backend/src/modules/pia-intake/dto/update-pia-intake.dto.ts
src/backend/src/modules/pia-intake/entities/pia-intake.entity.ts
src/backend/src/modules/pia-intake/pia-intake.controller.ts
src/backend/src/modules/pia-intake/pia-intake.module.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/src/modules/pia-intake/ro/create-pia-intake.ro.ts

- Added POST /pia-intake endpoint
**Note: PR with Test files to follow next to avoid muddling this one.**

[UTOPIA-436] added a POST pia-intake endpoint

---

openshift/templates/api/api-dc-template-v2.yaml
openshift/templates/app/app-dc-template-v2.yaml

UTOPIA-525: Review Long Running Quota Resources

UTOPIA-525: Review Long Running Quota Resources

---

src/backend/src/modules/pia-intake/dto/create-pia-intake.dto.ts

- updated pia-intake dto - riskMitigation and hasAddedPiToDataElements fields optional
Tested by calling swagger endpoint

[UTOPIA-436 fix-1] updated pia-intake dto - riskMitigation and hasAddedPiToDataElements fields optional

---

openshift/backup/README.md
openshift/backup/backup-build.yaml
openshift/backup/backup-deploy.yaml
openshift/backup/backup.conf

UTOPIA-530: Postgres Backup Containers

UTOPIA-530: Postgres Backup Containers

---

src/frontend/src/components/public/PPQConnect/index.tsx

- remove back btn in ppq-connect page
- 

[UTOPIA-396]remove back btn in ppq-connect page

---

src/frontend/src/components/common/Dropdown/_dropdown.scss
src/frontend/src/components/common/Dropdown/index.tsx
src/frontend/src/components/common/Dropdown/interfaces.ts
src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/components/common/Navbar/_navbar.scss
src/frontend/src/components/common/Navbar/index.tsx
src/frontend/src/components/common/Navbar/navPages.ts
src/frontend/src/constant/apiRoutes.ts
src/frontend/src/constant/routes.ts
src/frontend/src/pages/PIAIntakeForm/PIAIntakeFormPage.tsx
src/frontend/src/pages/PIAIntakeForm/messages.ts
src/frontend/src/pages/PPQFormPage/PPQFormPage.scss
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx
src/frontend/src/pages/PPQPage/PPQPage.tsx
src/frontend/src/routes/router.tsx
src/frontend/src/sass/_default.scss
src/frontend/src/sass/_form.scss
src/frontend/src/sass/common.scss
src/frontend/src/sass/index.scss
src/frontend/src/types/interfaces/pia-intake.interface.ts
src/frontend/src/types/interfaces/pia-result.interface.ts

_My apologies for the large PR_
- Implements form UI from Figma designs
- Creates interfaces related to PIA Intake form and submission
- Adds _form.scss file
- Implements PIA Intake form submission POST request
- Creates Dropdown component
- Visually assessed styling
- Firefox
- Chrome
- Filled out form and submitted

UTOPIA-433 & 435: Frontend Create Form UI & Integrate Frontend with API Endpoint

---

src/frontend/src/components/common/Navbar/navPages.ts

- Removes PIA Intake NavLink from navbar
Spun up application and checked that the NavLink for PIA Intake was longer present.

UTOPIA-536: Remove PIA Intake NavLink

---

src/backend/src/common/helpers/pdf-helper.ts
src/backend/src/modules/pia-intake/pia-intake.controller.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/src/modules/pia-intake/templates/pia-intake-result.pug
src/backend/src/modules/ppq/ppq.controller.ts
src/backend/src/modules/ppq/ppq.service.ts
src/backend/src/modules/ppq/templates/ppq-result.pug

- pia-intake /download/:id endpoint implementation
- PDF code refactor to avoid duplicates
Tested via swagger

[UTOPIA-439] pia-intake pdf download endpoint + pdf refactor

---

src/backend/package.json

- updated module mappers regex to fix the failing build
ran `npm run test` to ensure they are working as expected. will have to see how they work in the OS env

[UTOPIA-527-fix-1] build fix: corrected regex to better suite moduleNameMappers

---

src/backend/src/modules/pia-intake/dto/create-pia-intake.dto.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts

`src` included a reference from `test` folder - making build one level deeper, eventually failing `node dist/main` run
- added mock data directly in the src file
Ran a prod build on local to verify if the change works.

[UTOPIA-527-fix-2] build fix: ts compilation fix

---

src/frontend/src/routes/router.tsx

- add a new route to protected application from unauthorized  user access, if use is not login, just redirect them to landing page

[Utopia 380] add protected route

---

src/frontend/src/pages/PIAIntakeForm/PIAIntakeFormPage.tsx
src/frontend/src/pages/PIAIntakeForm/messages.ts

- Removes text below PIA Intake form title, as per PO request
Visually asserted that the PIA Intake form no longer contained text under the title.

UTOPIA-542: Remove text below PIA Intake form title

---

src/frontend/src/pages/PPQPage/PPQPage.scss
src/frontend/src/pages/PPQPage/PPQPage.tsx

[UTOPIA-401]fix home page css

---

src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/pages/PIAIntakeForm/messages.ts
src/frontend/src/pages/PPQPage/messages.ts

- Amends copy on homepage to reflect changes requested by PO
- Remedies a few minor prettier / linting errors
Visual assessment of changes to homepage copy

UTOPIA-544: Copy Revision

---

src/frontend/src/pages/PPQPage/PPQPage.scss

- remove height for container and add a padding in bottom 
- update css for home page

[UTOPIA-401] fix home page img over flow issue

---

src/frontend/src/components/public/PIAIntakeResults/index.tsx
src/frontend/src/components/public/PPQConnect/PPQConnect.scss
src/frontend/src/sass/_default.scss
src/frontend/src/sass/_form.scss
src/frontend/src/sass/_variables.scss
src/frontend/src/sass/common.scss

```diff
+ Fixes styling of PIA Intake results page to match Figma designs
+ Remedies minor linting errors
```

UTOPIA-438: Frontend Design Updates

---

src/frontend/src/pages/PIAIntakeForm/PIAIntakeFormPage.tsx

```diff
+ The default selection for question #4 of the PIA Intake form is now 'Yes'
```

UTOPIA-545: Change Q4 Default Selected Option

---

src/frontend/src/routes/router.tsx

- remove protected route code to unblock prod deployment

remove protected route

---

src/backend/test/unit/pia-intake/pia-intake.controller.spec.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts
src/backend/test/util/mocks/repository/repository.mock.ts
src/backend/test/util/mocks/services/pia-intake.service.mock.ts

- Five unit tests related to pia-intake pdf download endpoint
- Rearranged imports alphabetically
Tested the tests by running the tests. `cd src/backend && npm run test`

[UTOPIA-531] [Backend] [Unit Tests] added pia-intake download pdf endpoint unit tests

---

.github/workflows/build-deploy-api-v2.yaml
.github/workflows/build-deploy-app-v2.yaml
.github/workflows/tag-deploy-api-prod.yaml
.github/workflows/tag-deploy-api-test.yaml
.github/workflows/tag-deploy-app-prod.yaml
.github/workflows/tag-deploy-app-test.yaml

UTOPIA-453: Updating actions/checkout to v3

UTOPIA-453: Updating actions/checkout to v3

---

.github/workflows/build-deploy-api-v2.yaml

UTOPIA-453: Update Redhat Actions

---

.github/workflows/build-deploy-api-v2.yaml

UTOPIA-453: Troubleshooting New Redhat Actions

UTOPIA-453: Troubleshooting New Redhat Actions

---

.github/workflows/build-deploy-api-v2.yaml

UTOPIA-453: Troubleshooting Redhat Github Actions

UTOPIA-453: Troubleshooting Redhat Github Actions

---

src/frontend/.docker/Dockerfile

- Attempt to fix the permission set needed by OpenShift to let NGINX run with the minimum folders
Not tested. Will be done in dev.

[UTOPIA-565] [Frontend] [Docker] Updated NGINX permissions to suit OpenShift

---

.github/workflows/build-deploy-api-v2.yaml
.github/workflows/build-deploy-app-v2.yaml
.github/workflows/tag-deploy-api-prod.yaml
.github/workflows/tag-deploy-api-test.yaml
.github/workflows/tag-deploy-app-prod.yaml
.github/workflows/tag-deploy-app-test.yaml

UTOPIA-455: Redhat Openshift Actions Update

UTOPIA-455: Redhat Openshift Actions Update

---

src/frontend/.stylelintrc.js
src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/components/common/Modal/index.tsx
src/frontend/src/pages/LandingPage/LandingPage.tsx

- fix the frontend lint issue
- [] Bug fix (non-breaking change which fixes an issue)

[UTOPIA-540]add a new regex to check class seletcor name to by pass bem error

---

src/backend/src/common/entities/base.entity.ts
src/backend/src/modules/pia-intake/pia-intake.controller.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.controller.spec.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts
src/backend/test/util/mocks/services/pia-intake.service.mock.ts

- Added pia-intake findAll endpoint
- default sort is set to latest updatedAt
- Test cases accompanying the changes
This endpoint will return all the pia-intakes matching the following criteria by default
* - user's self submitted pia-intakes
* - [#TODO UTOPIA-482] if mpo, all pia-intakes submitted in the user's ministry
Tested via swagger.

[UTOPIA-481] [Backend] added pia-intake findAll endpoint

---

.gitignore
src/backend/package.json

- Updated Unit Test Code Coverage path
- Added coverage folder to gitignore
Verified by running `npm run test:cov`

[UTOPIA-568] [Backend] updated unit test code coverage path + add it to gitignore

---

src/frontend/src/components/common/NotFound/_notfound.scss

- Fixes styling issues on 404 page
Went to 404 page both, as a user who is authenticated, and one who is not. Styling remained visually consistent across both tests, with the exception of the navbar being present for an authenticated user.

UTOPIA-571: Fix Unauthenticated 404 Visual Bug

---

src/frontend/src/components/public/PIAListTable/index.tsx
src/frontend/src/components/public/PIAListTable/interface.ts
src/frontend/src/constant/apiRoutes.ts
src/frontend/src/hooks/usePIALookup.ts
src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/pages/PIAListPage/index.tsx
src/frontend/src/types/interfaces/pia-intake.interface.ts
src/frontend/src/types/interfaces/pia-result.interface.ts
src/frontend/src/utils/date.ts

- get all pia list from backend and render to frontend table

[Utopia 480] integrate with backend to get all list pia

---

src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/pages/PIAListPage/index.tsx

- 'Create New +' button on the PIA list page takes the user to the PIA Intake page
- BC Gov logo in header redirects user to DPIA Landing Page on click
- The default state of question 4 of the PIA Intake form is now `true`, which reflects the default checked option

UTOPIA-575: PIA List 'Create New +' Redirect

---

src/frontend/src/components/public/PIAListTable/index.tsx

- Hard codes all PIAs in PIA list to have the 'Submitted' status
Visually assessed that PIAs in PIA list have 'Submitted' status

UTOPIA-578: Hard Code PIA List Submitted Statuses

---

.github/workflows/build-deploy-app-v2.yaml

UTOPIA-583: Add Github Action to execute Cypress e2e test suite in DEV

UTOPIA-583: Add Github Action to execute Cypress e2e test suite in DEV

---

src/frontend/src/pages/PIAListPage/index.tsx

- Changes the redirect for the 'Create New +' button so that it now redirects to the PPQ/PIA info page 
Clicked the 'Create New +' button and asserted that the redirect was to the correct page

UTOPIA-575: PIA List 'Create New +' Redirect — Rev. 1

---

src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/constant/routes.ts
src/frontend/src/pages/LandingPage/LandingPage.tsx

- Fixes incorrect behaviour where upon logging in, the user is redirected to the PPQ/PIA info page
- Correct behaviour is to be redirected to PIA List
Logged in to application and was redirected to the PIA List.

UTOPIA-587: Login directs user to Info page

---

src/frontend/src/pages/PIAListPage/index.tsx

- Conditionally renders the EmptyPiaList component when the array length of PIAs is 0
Navigated to PIA list with no PIAs and saw EmptyPiaList component. Made a PIA and checked the PIA list page again where upon the PIA list was shown with the newly created PIA.

UTOPIA-588: User cannot see empty state of the table

---

src/backend/src/health/health.controller.ts

- made `/api/health` endpoint unprotected for Health checks
Swagger

[UTOPIA-592] [Backend] [Build Failure fix] Making Health endpoint unprotected

---

src/backend/src/modules/auth/auth.controller.ts

Currently, with only access token implementation if the user is logged out of the application while being on the app screen, there is no way to log out except via developer console. Making the Logout API unprotected to remove that restriction. 
The endpoint has to be added back to Protected once Refresh Token implementation is done.
- Making Logout unprotected
via swagger

[UTOPIA-590] [Backend] Making Logout unprotected until refresh token implementation is done

---

src/backend/src/modules/auth/guards/roles.guard.ts

- Fix for App breaks when user submits a PIA and has no client roles assigned

[UTOPIA-599] [Backend] Role Guard null check when user has no client roles assigned - Fix

---

adr-log/nginx-for-web-server.md
adr-log/puppeteer-for-pdf.md

- ADR for using NGINX as our web server
- Formatting update to puppeteer ADR
N/A

[UTOPIA-569] [Backend] [Documentation] [ADR] Using Nginx as web server

---

.github/workflows/code-climate.yaml
README.md
src/backend/package.json

[Squashed commit of code-climate-api-unit-test-coverage branch]
- [UTOPIA-615] Code Climate Test Aggregation + Submit
- [UTOPIA-613] API - Code Climate Test Generation
Tested by running Github Action and running the binary locally

[UTOPIA-615] Code Climate Test generation and upload

---

src/frontend/src/components/common/Breadcrumbs/_breadcrumbs.scss
src/frontend/src/components/common/Breadcrumbs/index.tsx
src/frontend/src/pages/PPQPage/PPQPage.tsx

- Positions the breadcrumbs component just under the application's navbar
- This PR does NOT address the re-usability of the breadcrumbs component 
Visual assertion.

UTOPIA-597: Make breadcrumbs position to navbar component absolute 

---

src/frontend/src/components/common/Modal/index.tsx
src/frontend/src/components/common/Modal/interfaces.ts
src/frontend/src/pages/PIADetailPage/index.tsx
src/frontend/src/pages/PIADetailPage/messages.ts
src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/pages/PIAIntakeForm/messages.ts

- add PIA form submission function

[UTOPIA-609]add pia submission feature

---

src/frontend/src/pages/PIAIntakeForm/index.tsx

- change save changes btn navigate action. 

[UTOPIA-608]change save changes button navigate to detail page instead list page

---

src/frontend/src/utils/storage.ts

- Bug fix for the interim period when browser is storing strings differently parsed than what it is now [standardized]
- This change can be reverted after a month or two when all the existing users would have logged out or auto logged out atleast once
// if the storage is compromised, log the user out
// This change is temporary and is due to the recent migration from storing localStorage directly vs using the newly created Storage class
// This can be reverted in the future as it can only happen for roles, and username keys [other field keys are changed]

[UTOPIA-465]  bug-fix: storage parsing interim error

---

src/frontend/src/routes/router.tsx
src/frontend/src/utils/helper.util.ts

- Removed additional parsing that was breaking the code
- JSON.parse on top of existing parsed result

[UTOPIA-465] Bug fix: Storage parsing on a parsed object

---

src/frontend/src/pages/PIAIntakeForm/index.tsx

- [Possibly this got missed testing] User was not able to JUST save when there is a new PIA being created

[Frontend] bug fix when user saves before submitting for the new pia

---

README.md

Making changes to the root level readme file

UTOPIA-667: rewrite root level readme.md

---

.github/workflows/build-deploy-api-v2.yaml
.github/workflows/build-deploy-app-v2.yaml
.github/workflows/tag-deploy-api-prod.yaml
.github/workflows/tag-deploy-api-test.yaml
.github/workflows/tag-deploy-app-prod.yaml
.github/workflows/tag-deploy-app-test.yaml

renaming each github action job to be more readable in the actions tab of the repo

making the github actions job naming convention a more readable

---

.github/workflows/code-climate.yaml

Code Climate Github Action Title Description

---

.github/workflows/test-push-artifactory.yaml

UTOPIA-475: Create Artifactory Project b996e6-tools

UTOPIA-475: Create Artifactory Project b996e6-tools

---

.github/workflows/pr-labeller.yaml

updating file name in labeller action

---

.github/workflows/test-push-artifactory.yaml

Changing login method to artifactory service

UTOPIA-475 - Changing Artifactory Login Method

---

.github/workflows/test-push-artifactory.yaml

UTOPIA-475: Typo in docker tag step

UTOPIA-475: Typo in docker tag step

---

src/frontend/src/pages/PIAIntakeForm/index.tsx

- Adds a line specifying the modal button value in the handleShowModal func on PIA intake form page
Clicked 'Submit' on PIA intake but cancelled before confirming and then saved instead. Asserted correct status after saving.

UTOPIA-687: [Frontend] Fix incorrect status change on submit cancel

---

.github/workflows/test-push-artifactory.yaml

UTOPIA-475: Updating typos in Docker Push

UTOPIA-475: Updating typos in Docker Push

---

src/backend/src/modules/pia-intake/dto/pia-form-query.dto.ts
src/backend/src/modules/pia-intake/pia-intake.controller.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.controller.spec.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts

- add search endpoint to support search by title or drafter name

[UTOPIA-561]add backend search endpoint to support search by title or drafter name

---

.github/workflows/test-push-artifactory.yaml

UTOPIA-475: Complete URL for tag and push

UTOPIA-475: Complete URL for tag and push

---

src/backend/src/modules/pia-intake/dto/create-pia-intake.dto.ts
src/backend/src/modules/pia-intake/dto/pia-form-query.dto.ts

- fix the backend api can not start issue. due to import a file from test folder cause dist folder structure change. rollback the change and import from src folder

remove import from test folder to fix nestjs build issue

---

.github/workflows/test-push-artifactory.yaml

UTOPIA-475: Updates to docker tag and push

UTOPIA-475: Updates to docker tag and push

---

src/backend/src/modules/pia-intake/dto/pia-intake-find-query.dto.ts
src/backend/src/modules/pia-intake/pia-intake.controller.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.controller.spec.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts

- Removed /search endpoint and add searchText queryParam to findAll endpoint
- Single search field now searches for both drafter and title
- Search is case insensitive now
- Added searchText trims and value default to empty string ''

[UTOPIA-561] Refactor search -

---

src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

- Followup to #754 to reduce flagged cognitive complexity by Code Climate

[UTOPIA-561] [Search PIAs] Attempt to reduce cognitive complexity

---

.github/workflows/test-push-artifactory.yaml

Changing image tag from latest to prod to match a tag in artifactory

UTOPIA-475: Changing image tag

---

.github/workflows/test-push-artifactory.yaml

UTOPIA-475: Changing Docker Push

---

.github/workflows/test-push-artifactory.yaml

UTOPIA-475: changing back to latest tag

---

src/backend/src/modules/pia-intake/dto/pia-intake-find-query.dto.ts
src/backend/src/modules/pia-intake/pia-intake.controller.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.controller.spec.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

- Added pagination to PIA-intake findAll endpoint
Swagger

[UTOPIA-557] added pagination to pia-intake

---

src/backend/src/common/enums/sort-order.enum.ts
src/backend/src/modules/pia-intake/constants/pia-intake-allowed-sort-fields.ts
src/backend/src/modules/pia-intake/dto/pia-intake-find-query.dto.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts

- adding sort to pia-intake findAll endpoint
Created a followup sub-issue which I am working on the side [UTOPIA-700](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-700)
Swagger

[UTOPIA-554] adding sort to pia-intake findAll endpoint

---

src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/components/common/SearchBox/index.tsx
src/frontend/src/components/common/SearchBox/interfaces.ts
src/frontend/src/hooks/usePIALookup.ts
src/frontend/src/pages/PIAListPage/index.tsx
src/frontend/src/routes/router.tsx
src/frontend/src/sass/_buttons.scss
src/frontend/src/sass/_form.scss

- add search ui in pia table view and integrate with backend API

[Utopia 560] add search box UI

---

.github/workflows/test-push-artifactory.yaml

UTOPIA-475: Updating Artifactory Location

---

src/backend/package-lock.json
src/backend/package.json

- manually updated @nestjs/mapped-types 's package-lock - to include not-infected 0.14.0 class-validator
- class-validator update to 0.14.0
- updated nest* versions to latest
Follow up ticket - https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-702
Tested the flow. Created/View PIA

[UTOPIA-678] [Backend] class-validator update; explicitly updated @nestjs/mapped-types; updated nest versions

---

.github/workflows/test-push-artifactory.yaml
openshift/templates/api/api-dc-template-artifactory.yaml
openshift/templates/api/api-route-template-artifactory.yaml
openshift/templates/api/api-service-template-artifactory.yaml

Deploying API Image from Artifactory

UTOPIA-475: Deploying API Image from Artifactory

---

src/backend/src/modules/pia-intake/dto/create-pia-intake.dto.ts
src/backend/src/modules/pia-intake/dto/pia-intake-find-query.dto.ts
src/backend/src/modules/pia-intake/enums/pia-filter-drafter-by-current-user.enum.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

-add backend function for filter

[Utopia-562] add filter pia by drafter/status/ministry in backend

---

src/backend/src/modules/pia-intake/dto/pia-intake-find-query.dto.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

- Added test case for Sort
- Refactor filter logic for enums
Running test and via swagger

[UTOPIA-699] added sort test + updated filter logic for enums

---

src/frontend/src/components/common/Pagination/index.tsx
src/frontend/src/sass/_pagination.scss

[Utopia 712] - Pagination - Fix clicking elemnets in table dropdown

---

openshift/templates/api/api-dc-template-artifactory.yaml

adding template and parameters missing from yaml in order to deploy

UTOPIA-475: Artifactory - missing template and parameters in api yaml file

---

src/backend/src/migrations/1674601836799-pia-intake-allow-null-all.ts
src/backend/src/modules/pia-intake/dto/create-pia-intake.dto.ts
src/backend/src/modules/pia-intake/entities/pia-intake.entity.ts
src/backend/src/modules/pia-intake/pia-intake.controller.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/src/modules/pia-intake/ro/create-pia-intake.ro.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

- Enable Partial Save - all columns can be empty; Migration added to drop NOT null constraint from all columns
- Fix @UpdatedAtDate column by using .save instead of .update
- Return complete pia object as response instead of just the id

[Utopia 709] Enable Partial Save + fix UpdatedAt column + return complete object on create pia

---

.github/dependabot.yaml

updating directories for dependabot scans

UTOPIA-731: Updating Dependabot Yaml

---

.github/workflows/zap-frontend-scan.yaml

UTOPIA-733: Update ZAP Scan for Frontend, day and time

UTOPIA-733: Update ZAP Scan for Frontend, day and time

---

.github/workflows/test-push-api-artifactory.yaml
.github/workflows/test-push-app-artifactory.yaml

UTOPIA-475: Adding test pipeline for webapp to artifactory

UTOPIA-475: Adding test pipeline for webapp to artifactory

---

.github/workflows/zap-api-scan.yaml

UPTOPIA-732: Update ZAP Scan API URL, day and time

UTOPIA-732: Update ZAP Scan API URL, day and time

---

.github/workflows/build-deploy-api-v2.yaml

UTOPIA-737: Adding Success Notification to Teams Channel

UTOPIA-737: Adding Success Notification to Teams Channel

---

.github/workflows/zap-frontend-scan.yaml
src/frontend/index.html
src/frontend/nginx.conf

- Added security headers taking suggested reference from https://github.com/bcgov/jag-file-submission/blob/master/src/frontend/efiling-frontend/nginx.conf
- Fixes https://github.com/bcgov/cirmo-dpia/issues/724
If the next ZAP scan again throws the error, we can follow this article to add more headers from this link - https://forum.level1techs.com/t/infrastructure-series-http-s-security-headers-you-should-use-them-nginx/171235

UTOPIA-736: [Nginx] Added security headers

---

.github/workflows/build-deploy-api-v2.yaml

Typo In Github Action

---

src/frontend/src/components/common/Alert/index.tsx
src/frontend/src/components/common/Alert/interfaces.ts
src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/components/common/Modal/index.tsx
src/frontend/src/components/common/Pagination/index.tsx
src/frontend/src/components/public/PIAIntakeResults/index.tsx
src/frontend/src/pages/PIADetailPage/index.tsx
src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/pages/PIAIntakeForm/messages.ts
src/frontend/src/pages/PIAIntakeResultsPage.tsx
src/frontend/src/types/interfaces/pia-intake.interface.ts
src/frontend/src/utils/date.ts
src/frontend/src/utils/object-comparison.util.ts

- AutoSave functionality added to FE
- PIA form refactor
- Affected areas refactor

[Utopia 673] [Frontend] AutoSave functionality + PIA form refactor

---

.github/workflows/build-deploy-api-v2.yaml

Typo In Git Action

---

src/frontend/nginx.conf

- Weird image src on dev fix
https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-742

[UTOPIA-742] Content Security Policy Headers - img-src fixed

---

src/frontend/src/components/common/Pagination/index.tsx
src/frontend/src/components/public/PIAIntakeFilter/index.tsx
src/frontend/src/components/public/PIAIntakeFilter/interfaces.ts
src/frontend/src/hooks/usePIALookup.ts
src/frontend/src/pages/PIAListPage/index.tsx

- fix search text and filter relation when do query

[Utopia 720] fix search text and filter to and relation instead of or 

---

src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

- please see JIRA for [detail](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-714)
- this will make sure if the user chooses filter by the ministry, the query will only return the chosen ministry's pia if and only if the current user has the access to see this ministry's PIAs. otherwise, we will return an empty array to the frontend.

[UTOPIA-714]fix filter by ministry will return the wrong results

---

.github/workflows/build-deploy-app-v2.yaml
.github/workflows/tag-deploy-app-prod.yaml
.github/workflows/tag-deploy-app-test.yaml

UTOPIA-737: adding success and failure notifications for webapp deployment

UTOPIA-737: adding success and failure notifications for webapp deployment

---

src/frontend/src/components/common/Breadcrumbs/_breadcrumbs.scss
src/frontend/src/components/common/Pagination/index.tsx
src/frontend/src/pages/PIADetailPage/index.tsx
src/frontend/src/pages/PPQPage/PPQPage.tsx
src/frontend/src/sass/_default.scss
src/frontend/src/sass/_pagination.scss

Utopia-688 - Fix breadcrumb alignmnent

---

src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

- updated filter logic for exclude/include self PIAs

[UTOPIA-746] updated filter logic for exclude/include self PIAs

---

src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

-bug detail(https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-716)
the mpo should not see other drafters' incomplete status pia for their ministries
This also fixes FilterByMinistry filter override issues.

[UTOPIA-716]  MPO can only see pia status is non-incomplete for other drafters; ALSO updated filterByMinistry fix

---

src/frontend/src/pages/PIADetailPage/index.tsx

- Incomplete status Alert not working + Refactor PIA detail page
Testing by opening Incomplete PIA details. Observe warning alert is now visible

[UTOPIA-748] [Frontend] Incomplete status Alert not working - fix + Refactor PIA detail page

---

src/frontend/src/pages/PIAIntakeForm/index.tsx

…
- warning message on tab close shows even when there aren't any changes to save - fix
Close tab before autosave happens within 3 seconds of typing last character

[UTOPIA-744] [Frontend] warning message on tab close shows even when there aren't any changes to save - fix

---

src/frontend/src/hooks/usePIALookup.ts
src/frontend/src/pages/PIAListPage/index.tsx

- For more details please see [link](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-366)
- if the user deletes the search text, then search it,the app will still use the previous value instead delete this param from searchParams object.
- the fix will check if the searchText is empty string then delete the searchText from params object

[UTOPIA-366]fix searchText box empty value not handle properly 

---

.github/workflows/build-deploy-app-v2.yaml
.github/workflows/tag-deploy-app-test.yaml

Notification of deploy to dev/test happens after e2e suite is run.

UTOPIA-737: Changing Order of Notifications on Frontend

---

openshift/templates/api/api-dc-template-artifactory.yaml
openshift/templates/api/api-dc-template-v2.yaml

- Adds new env vars to the api openshift deployment configs

UTOPIA-677: API Deployment Config Env Vars 

---

openshift/templates/api/api-dc-template-artifactory.yaml
openshift/templates/api/api-dc-template-v2.yaml

UTOPIA-677: Fixes typo in api dc templates.

---

src/frontend/src/components/common/AppActivityManager/index.tsx
src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/utils/auth.ts
src/frontend/src/utils/function.ts
src/frontend/src/utils/storage.ts

…better performance
- Tracking and syncing user activity across browser tabs
- Enabled Throttling for better permormance 
Keep two simultaneous application tabs open. Work on one and leave the other one idle. Notice you're not logged out anymore when you're active on atleast one tab for 15mins.

[Frontend] Bug fix: Users are logged out of one tab but active in an another tab

---

src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/src/modules/pia-intake/templates/pia-intake-result.pug

- [Backend] updated PIA Intake PDF template with Signatures;
- Updated Last modified field and value
Create PIA-intake. Download pdf to see the bottom section with Signature appear.

[UTOPIA-776] [BE] update PDF template / Add Signature Block - Delegated Review 

---

src/frontend/src/pages/PIADetailPage/index.tsx

[UTPOPIA-675]dispaly N/A when submittedAt date is null in detail page

---

.github/workflows/npm-audit-api.yaml
.github/workflows/npm-audit-frontend.yaml

UTOPIA-784: NPM Audit on Pull Request
[Documentation](https://github.com/marketplace/actions/npm-audit-action)

UTOPIA-784: NPM Audit on Pull Request

---

src/frontend/src/pages/PiaFormPage/index.tsx
src/frontend/src/routes/router.tsx

- added new /pia routes
- To remove ref of prev router [UTOPIA-808](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-808)
Manually going and traversing to /pia route

[FE] added new /pia routes

---

src/frontend/src/components/public/PIAFormTabs/README.md

Utopia-809 Create folder structure for form tabs

---

src/frontend/src/components/common/Breadcrumbs/index.tsx
src/frontend/src/components/common/Navbar/navPages.ts
src/frontend/src/components/public/PIASubHeader/_piasubheader.scss
src/frontend/src/sass/_form.scss
src/frontend/src/sass/_variables.scss

- [UTOPIA-810] Bug fix - white header styling issues
- [UTOPIA-810] Bug fix 2 - subHeader - added box shadow and styling fixes
- [UTOPIA-812] Bug fix - subHeader - name change for nav items
--

[UTOPIA-759 - bug fixes]

---

src/frontend/src/sass/_default.scss

[bug fix] top padding moved after prev change

---

src/frontend/src/components/public/PIAFormTabs/intake/index.tsx
src/frontend/src/components/public/PIAListTable/index.tsx
src/frontend/src/constant/routes.ts
src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/routes/router.tsx

- Fix: Form inputs are acting weird after parent-child forms
- Missed routes mapping to routes constant

[UTOPIA-774-bug-fix] [Frontend] Fix: Form inputs are acting weird after parent-child forms

---

.github/workflows/emerald-push-api-artifactory.yaml

UTOPIA-831: Push API image to artifactory project linked to emerald cluster

UTOPIA-831: Push API image to artifactory project linked to emerald cluster

---

src/frontend/src/components/common/Navbar/index.tsx
src/frontend/src/components/common/Navbar/interfaces.ts
src/frontend/src/components/public/PIAFormTabs/intake/index.tsx
src/frontend/src/components/public/PIAListTable/index.tsx
src/frontend/src/components/public/PIASideNav/index.tsx
src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts
src/frontend/src/constant/routes.ts
src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/routes/router.tsx
src/frontend/src/sass/_default.scss
src/frontend/src/sass/_sideNav.scss
src/frontend/src/sass/_variables.scss
src/frontend/src/utils/path.ts

- Routing fixed
-  PIA side navigation styling fix

[UTOPIA-813] Routing and PIA side navigation fix

---

openshift/templates/rolebindings/ey-developers-idir-edit.yaml

UTOPIA-839: Updating Icaro Oliveira Idir in Openshift Rolebinding

UTOPIA-839: Updating Icaro Oliveira Idir in Openshift Rolebinding

---

.github/workflows/emerald-push-app-artifactory.yaml

UTOPIA-831/832: Changing API + WebApp image tag, renaming workflow file

---

openshift/templates/api/api-dc-template-artifactory.yaml

UTOPIA-852: Updating API K8s Template to reflect Emerald cluster

UTOPIA-852: Updating API K8s Template to reflect Emerald cluster

---

src/frontend/src/components/public/PIAFormTabs/PIAAdditionalRisks/index.tsx

[UTPOIA-843]add a check to make sure addtional tab render 4 rows initial phase

---

openshift/templates/api/api-dc-template-artifactory.yaml

UTOPIA-855: Updating API template for network policy name matching

UTOPIA-855: Updating API template for network policy name matching

---

openshift/templates/network-policies/emerald/postgres-network-policy-template.yaml

Changing Postgres Egress policy to match feedback provided from platform services

UTOPIA-855: Egress Policy Feedback

---

src/backend/src/modules/auth/auth.controller.ts
src/backend/src/modules/auth/auth.service.ts
src/frontend/src/components/common/AppActivityManager/index.tsx
src/frontend/src/utils/auth.ts

- [server log crashing inside catch - fix](https://github.com/bcgov/cirmo-dpia/commit/9ab2efbba013de3d1786c4db7f583c5992e86cc4)
- [[UTOPIA-856] refresh token logs not actually refreshing tokens - fix](https://github.com/bcgov/cirmo-dpia/commit/1f6d66f67733daaef43b48123d5c533108fef4ba) - "Unexpected end of JSON input in console - fix"

[UTOPIA-856] Server crash - fix + Refresh Token not actually refreshing - fix

---

openshift/templates/api/api-dc-template-artifactory.yaml
openshift/templates/network-policies/emerald/api-network-policy-template.yaml
openshift/templates/network-policies/emerald/postgres-network-policy-template.yaml

- network policy name typo for postgres container
- adding name and dataclass label to api pod in dc template

UTOPIA:855: Typos network policies

---

openshift/templates/network-policies/emerald/api-network-policy-template.yaml
openshift/templates/network-policies/emerald/postgres-network-policy-template.yaml

UTOPIA-855: correct network policies for api/db connection

UTOPIA-855: correct network policies for api/db connection

---

src/frontend/src/components/public/PIAFormTabs/Security_Personal_Information/helper/messages.ts
src/frontend/src/components/public/PIAFormTabs/Security_Personal_Information/index.tsx
src/frontend/src/components/public/PIAFormTabs/Security_Personal_Information/security-personal-info-interface.ts
src/frontend/src/routes/router.tsx
src/frontend/src/sass/_callout.scss
src/frontend/src/sass/_default.scss
src/frontend/src/sass/_form.scss
src/frontend/src/sass/_sideNav.scss
src/frontend/src/sass/common.scss
src/frontend/src/types/interfaces/pia-form.interface.ts

Utopia-770 Tab Security Personal Information

---

src/backend/src/migrations/1678142798474-piaIntakeAddColumnsNextStepFlags.ts

- Remove Test column from migration

[UTOPIA-848] migration crash fix

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/helper/messages.ts
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx

- update accuracy retention tab logic for last question
- update external link and icon
Expected result:
If yes- do NOT display next question
if no - display next question

[Utopia 867] fix tab accuracy

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/helper/messages.ts
src/frontend/src/components/public/PIAFormTabs/intake/index.tsx
src/frontend/src/constant/constant.ts
src/frontend/src/pages/PIAIntakeForm/index.tsx

Utopia-883 fix submit PIA based on PI

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/components/public/PIAFormTabs/additionalRisks/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx

- Only touches tabs that were missing this implementation
- Currently, storingPersonalInformation tab isn't 100%
Go through PIA tabs and check for correct behaviour and correct data, i.e.: Autosave is green and the API responds with the correct data.

UTOPIA-859: [Stale data passed error] call piaStateChangeHandler using useEffect for all tabs

---

src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/messages.ts

- Correct typo in copy for storingPersonalInformation tab
N/a.

UTOPIA-885: Typo on first text area of Storing PI tab

---

src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx

- Replaces incorrect question text with correct text
- Adds relevent helper text to question
Visually assessed change.

UTOPIA-888: Incorrect Question

---

src/frontend/src/components/common/Table/index.tsx
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/components/public/PIAFormTabs/additionalRisks/AdditionalRisks.ts
src/frontend/src/components/public/PIAFormTabs/additionalRisks/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx
src/frontend/src/utils/function.ts
src/frontend/src/utils/object-modification.util.ts

- Created new common component for Tabular Data - Table. 
- Replaces the existing List component usage inside Additional Risks tab
- Also includes super cool way of updating nested states 🤩
Look & feel - good. #optimized

[UTOPIA-854] [Refactor] New Table Component. Replaces List for AdditionalRisks tab

---

src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx

- Answering 'No' on question 3 hides the rest of the form following that question
Visually assessed correct component rendering based on question response.

UTOPIA-887: Conditional logic fix for Assessment of disclosures outside of Canada

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/components/public/PIANavButton/index.tsx
src/frontend/src/components/public/PIANavButton/interface.ts
src/frontend/src/constant/routes.ts
src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/routes/router.tsx

[UTOPIA-860] add next and back btn for pia form

---

src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/CollectionUseAndDisclosure.ts
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx

- Refactoring Table and data inside CollectionUseAndDisclosure tab
Tested on app

[UTOPIA-854] [Refactor] [CollectionUseAndDisclosure]

---

src/backend/src/modules/pia-intake/dto/create-pia-intake.dto.ts

- [sadly] removing email validations as discussed
N/A. Autosave works with no failure.

[UTOPIA-869] remove email validations

---

src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx

- Refactor Security of PI
Look and feel

[UTOPIA-854] [Refactor] [SecurityPI]

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx

- Refactor of Accuracy, Correction and retention

[UTOPIA-854] [Refactor] [AccuracyRetention]

---

.github/workflows/npm-audit-api.yaml
.github/workflows/npm-audit-frontend.yaml

Update NPM Audit Github Action

---

src/frontend/src/components/common/CustomInputDate/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx

- Refactor AgreementsAndInfoBanks

[UTOPIA-854] [Refactor] [AgreementsAndInfoBanks]

---

src/backend/src/modules/pia-intake/pia-intake.controller.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.controller.spec.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts
src/frontend/src/utils/helper.util.ts

- PIA role access changes for certain fields which are MPO specific
By changing SSO permissions as we write in fields which are restricted by drafters

[UTOPIA-908] Updated PIA role access - you have an MPO access when you're MPO of any ministry

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/index.tsx
src/frontend/src/components/public/PIAFormTabs/Next_Steps/nextStepsDelegatedFlow.tsx
src/frontend/src/components/public/PIAFormTabs/Next_Steps/nextStepsPI.tsx

Utopia-925 Refactor NextSteps

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/nextStepsPI.tsx
src/frontend/src/pages/PIADetailPage/index.tsx

fix docker build failed

---

src/frontend/src/components/common/Checkbox/index.tsx
src/frontend/src/components/common/Checkbox/interfaces.ts
src/frontend/src/components/common/Dropdown/index.tsx
src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/components/common/Radio/index.tsx
src/frontend/src/components/common/Radio/interfaces.ts
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx
src/frontend/src/routes/router.tsx

- InputText component now has a check and render for 'not answered'
- isReadOnly is now handled by parent context rather than by passing prop in router
Checked for correct 'isReadOnly' behaviour by switching between edit and view via the url path.

UTOPIA-911: Small fixes

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/components/public/PIAFormTabs/additionalRisks/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx
src/frontend/src/components/public/PIAFormTabs/intake/index.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx
src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/components/public/PIASubHeader/interfaces.ts
src/frontend/src/pages/PIADetailPage/index.tsx
src/frontend/src/pages/PIAForm/index.tsx

- Next Steps multiple bugs resolved

[UTOPIA-890] next steps bug resolution

---

src/frontend/src/components/common/Checkbox/index.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/routes/router.tsx

- View mode for securityOfPersonalInformation tab
Visually asserted correct behaviour based on view vs edit mode.

UTOPIA-913: [FE] Tab - Security of Personal Information

---

src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/AgreementsAndInformationBanks.ts
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/viewISATextInput.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/viewPIBTextInput.tsx
src/frontend/src/routes/router.tsx

- agreements and personal information banks tab view mode

[UTOPIA-915] update aib tab for view mode

---

src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/helper/messages.ts
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx

- Adds links to question 2 of the securityOfPersonalInformation tab

UTOPIA-913: Question Two Links

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/routes/router.tsx

- Adds conditions for view mode rendering to the accuracy and retention tab
Visual assertion.

UTOPIA-914: [FE] Tab - Accuracy, correction and retention

---

src/frontend/index.html
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/helper/messages.ts
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx

[UTOPIA-815] correct app title and misspelling parameter name

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/index.tsx
src/frontend/src/constant/routes.ts
src/frontend/src/pages/PIAForm/index.tsx

- Next Steps bug fix for dev
- Submit button for New PIA
- Run locally - create new PIA

[UTOPIA-883] next steps bug fixes + submit button for new PIA text fix

---

src/backend/src/migrations/1678996557122-update-ministry-name.ts

- add new migration to update existing pia-intake form ministry name(if any)  to new ministry name 
- [] N/A

[UTOPIA-795]add migration to update ministry name

---

src/frontend/src/components/public/PIAFormTabs/additionalRisks/index.tsx
src/frontend/src/routes/router.tsx

- Readonly for Additional Risks Tab
- 
Viewing Additional Risk tab

[UTOPIA-916] add readonly for additional risks tab

---

src/backend/src/common/constants/gov-ministries.constant.ts
src/backend/src/common/constants/roles.constants.ts
src/backend/src/common/enums/roles.enum.ts

[UTOPIA-936] update acronym for post-second and future skill ministry

---

src/frontend/src/components/common/Alert/_alert.scss
src/frontend/src/components/common/Alert/index.tsx
src/frontend/src/components/public/PIASubHeader/_piasubheader.scss
src/frontend/src/components/public/PIASubHeader/index.tsx

- Styling/spacing updates for Subheader
- Auto Save alert box gap between icon and text
- More options is now a Dropdown
- NextSteps Status was getting cut - fix
Header look and feel

[UTOPIA-935] Subheader styling updates

---

src/frontend/src/components/common/Card/_card.scss
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx

- Adds view mode to the Storing Personal Information tab
Visual assertion via switching between 'view' and 'edit' modes.

UTOPIA-912: [FE] Tab - Storing Personal Information

---

src/backend/package-lock.json
src/backend/package.json

- updated nestjs/cli to 9.3.0 - High vulnerability fix
Builds fine. PR to check if 

[UTOPIA-940] updated nestjs/cli to 9.3.0 - High vulnerability fix

---

src/frontend/src/sass/_variables.scss

- Updated gutter space to 3rem, which is equal to 48px based on current font scheme of things.
Screenshot attached above.

[UTOPIA-938] updated gutter space

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/accuracy-retention-interface.ts
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx

- fix tab disclosure not answered not italicized and retention tab two  answer missing in view mode

[UTOPIA-944]fix tab disclosure retention tab view mode issues

---

src/frontend/src/pages/PPQPage/PPQPage.tsx
src/frontend/src/sass/_default.scss

- see screenshots
Large
Medium
Small

[UTOPIA-893]make create new page responsive

---

src/frontend/src/sass/_default.scss

Utopia-939 Update font size based on screen size

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/index.tsx
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/sass/_default.scss

- Removes `justify-content: center` from bcgovPageContainer css class
- Following repro steps from JIRA ticket
- Assessing other pages of the app for breaking changes 

UTOPIA-884: Spacing issues on Storing PI Tab

---

src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/components/common/Header/_header.scss

Utopia-953 update header to be responsive

---

src/frontend/src/pages/LandingPage/LandingPage.scss
src/frontend/src/pages/LandingPage/LandingPage.tsx

[UTOPIA-891]make landing page responsive

---

src/frontend/src/pages/PIAForm/index.tsx

No additional cases surrounding 'next steps' or submission of the PIA have been covered as these cases are encapsulated within other tickets.
- Adds additional checks for rendering the 'next steps' tab
- Removes extraneous fragment tag from 'next steps' tab
Submitted from pia intake under each condition to check for correct redirect.

UTOPIA-941: Submitting PIA Intake from Edit/Incomplete Nav issues

---

src/frontend/cypress/e2e/landing-page/landingpage.cy.ts

-  E2E test failed due to responsive change in header
AssertionError: Timed out retrying after 5000ms: Expected to find element: `.header-h1`, but never found it.

[add-hoc]fix e2e

---

src/frontend/src/components/common/Dropdown/index.tsx
src/frontend/src/components/common/Dropdown/interfaces.ts
src/frontend/src/components/common/SearchBox/index.tsx
src/frontend/src/components/public/PIAIntakeFilter/index.tsx
src/frontend/src/components/public/PIAListTable/index.tsx
src/frontend/src/pages/PIAListPage/index.tsx
src/frontend/src/pages/PIAListPage/tableProperties.ts
src/frontend/src/sass/_form.scss
src/frontend/src/sass/_table.scss

- Filter and search section responsive
- List Table changes - Title clickable, Drafter name only shown on larger screens
Check the app with different sizes

[UTOPIA-892] Responsive List PIA page

---

src/frontend/src/pages/LandingPage/LandingPage.scss
src/frontend/src/pages/LandingPage/LandingPage.tsx
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx

-  update inline paddings for create ppq form
- update landing page responsive design

[UTOPIA-895]update landing page and create  ppg form responsive

---

src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx

[UTOPIA-902] alignment issues fix

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/components/public/PIAFormTabs/additionalRisks/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx
src/frontend/src/components/public/PIAFormTabs/intake/index.tsx
src/frontend/src/components/public/PIAFormTabs/intake/viewGeneralInformation.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx
src/frontend/src/sass/_variables.scss

- minimal card spacing for smaller screen
`>=768px`
`<768px`

[UTOPIA-962] minimal card spacing for smaller screen

---

src/frontend/src/components/common/Modal/_modal.scss
src/frontend/src/components/common/Modal/index.tsx

- see title
add a new breakpoint for md 
before the fix

[UTOPIA-963]make modal responsive

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/helper/messages.ts
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/messages.ts

[UTOPIA-964]fix typo in text

---

src/frontend/src/components/common/Footer/Footer.tsx

[UTOPIA-907]add footer link

---

src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/components/common/Header/_header.scss

- Responsive Auth buttons
SignIn
SignOut

[UTOPIA-970] auth buttons responsive

---

src/frontend/src/components/common/Footer/Footer.tsx

[UTOPIA-981]update footer link so open in a new tab

---

src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx

[UTOPIA-976]fix spi tab logic error

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx

[UTOPIA-974]add missing question in retention tab view mode

---

src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx

-the spi tab question 2 set to no, the next question should pre-selected yes instead of no
Problem
Fix

[UTOPIA-880] update spi tab pre-selected question value

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx

[UTOPIA-968]change q2 in accuracy tab default value to yes

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/helper/messages.ts

- detail link in the ticket [868](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-868)

[UTOPIA-868]update accuracy tab links

---

src/frontend/src/utils/auth.ts
src/frontend/src/utils/http-request.util.ts

Bug Identified while Testing in Dev - Fixed
- User was always redirected to not-authorized on logout - fixed

[UTOPIA-909] BugFix that the user is always redirecting to not-authorized page on logout

---

src/frontend/src/pages/PIAForm/index.tsx

- save the current data to backend and go to the view mode for the same tab

[UTOPIA-945]update save button bahaviour in subheader,

---

.github/workflows/tag-deploy-api-test.yaml

UTOPIA-782: Pull DEV Artifactory image for tagging + promotion

---

src/frontend/src/components/public/PIAFormTabs/intake/index.tsx

- BUGFIX: allow ministry to be unselected; IN PROD as well
Steps to reproduce in the ticket.

[UTOPIA-994] BUGFIX: allow ministry to be unselected

---

.github/workflows/tag-deploy-app-test.yaml

UTOPIA-782: adding docker pull and list to test app deploy action

---

src/frontend/src/pages/PIAForm/index.tsx

- Restrict changes in view mode from chrome dev tools

[UTOPIA-997] Restrict changes in view mode from chrome dev tools

---

src/frontend/src/pages/PIAForm/index.tsx

- [UTOPIA-1000] AutoSave - stale fix when multiple changes are send in a row

[UTOPIA-1000] AutoSave - stale fix when multiple changes are send in a row

---

src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/components/common/SearchBox/index.tsx
src/frontend/src/components/common/SearchBox/interfaces.ts
src/frontend/src/pages/PIAListPage/index.tsx

- Instead of "enter" handling the complete web document, handle for a particular input field
- Fixes the enter restrict of the whole page
List page is accessible and clickable via tab

[UTOPIA-1003] event handler Accessibility fix for Search Text on List Page

---

src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/sass/_buttons.scss

- Fix 'Submit' button disabled pointer
Tested under repro steps.

UTOPIA-1006: PIA subHeader - submit button UI issue when disabled

---

src/frontend/src/components/public/PIAFormTabs/intake/index.tsx
src/frontend/src/pages/PIAForm/index.tsx

[UTPIA-1008 &998]fix can not submit full pia issue and remvoe dataElementInvolve validation check

---

src/frontend/src/pages/PIAForm/index.tsx

Error validation banner fix

---

.github/workflows/tag-deploy-api-prod.yaml
.github/workflows/tag-deploy-app-prod.yaml

UTOPIA-782: removing artifactory tag promotion

---

src/frontend/src/App.tsx

-fix skip to main content nav link 

[UTOPIA-1005]fix skip to main content nav link

---

src/frontend/src/components/common/Collapsible/index.tsx
src/frontend/src/components/common/Collapsible/interfaces.ts
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/sass/_collapsible.scss
src/frontend/src/sass/common.scss

- Creates & implements a wrapper component that takes in a fontawesome icon and an alignment (left or right) and makes it's children collapsible
Enclosed the PIA side navigation menu within the Collapsible component and it performs as expected.

UTOPIA-927: Implement Frontend Collapsible Component for sidebars

---

src/frontend/index.html
src/frontend/nginx.conf
src/frontend/snowplow.js

Added snowplow script as a file to avoid unsafe-eval

---

.husky/pre-commit
src/frontend/.eslintrc.js
src/frontend/src/components/common/Callout/_callout.scss
src/frontend/src/components/common/Callout/index.tsx
src/frontend/src/components/common/Callout/interfaces.ts
src/frontend/src/pages/LandingPage/LandingPage.scss
src/frontend/src/pages/LandingPage/LandingPage.tsx
src/frontend/src/pages/PIAForm/BannerStatus/index.tsx
src/frontend/src/pages/PIAForm/BannerStatus/interfaces.ts
src/frontend/src/pages/PIAForm/index.tsx

[Utopia 1012]  banner status update for next steps

---

.github/workflows/app-e2e.yaml

[E2E] Github workflow added

---

src/frontend/src/pages/PIAForm/BannerStatus/index.tsx
src/frontend/src/pages/PIAForm/BannerStatus/messages.ts

[UTOPIA-1021] update callout banner text  for pia

---

.github/workflows/tag-deploy-api-prod.yaml
.github/workflows/tag-deploy-app-prod.yaml

command / removed comments from previously commented out steps in prod api and app promotion steps.

BUG: missing # for comments in prod actions

---

.github/workflows/tag-deploy-api-prod.yaml
.github/workflows/tag-deploy-app-prod.yaml

BUG: missing indent on prod api and app github actions

BUG: missing indent on prod api and app github actions

---

.github/workflows/app-e2e.yaml
src/frontend/cypress.config.ts
src/frontend/cypress/e2e/login-page/loginpage.cy.ts

- Fix issue with the secret being called 
- Add new config file and pass argument directly

UTOPIA-336 Update the workflow with new approach and config file

---

.github/workflows/build-deploy-app.yaml

UTOPIA-336 Update build-deploy to point to dev

---

.github/PULL_REQUEST_TEMPLATE.md

Adding Pull Request Template Option for Updates to Tests

---

docker-compose.local.yaml
src/backend/src/app.module.ts
src/backend/src/common/helpers/base-helper.ts
src/backend/src/common/swagger.ts
src/backend/src/migrations/1681507013982-comments-entity.ts
src/backend/src/modules/comments/comments.controller.ts
src/backend/src/modules/comments/comments.module.ts
src/backend/src/modules/comments/comments.service.ts
src/backend/src/modules/comments/dto/create-comment.dto.ts
src/backend/src/modules/comments/dto/update-comment.dto.ts
src/backend/src/modules/comments/entities/comment.entity.ts
src/backend/src/modules/comments/enums/allowed-comment-paths.enum.ts
src/backend/src/modules/comments/ro/get-comment.ro.ts
src/backend/src/modules/pia-intake/pia-intake.module.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts
src/frontend/src/types/interfaces/pia-form.interface.ts

- Comment Entity added
- Migration ran
- POST endpoint to create a comment
- GET endpoint to fetch comments by piaId and path created
- DELETE endpoint to soft delete a comment
Includes implementation of tickets: 
[UTOPIA-692](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-692),
[UTOPIA-693](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-693),
[UTOPIA-694](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-694), 
[UTOPIA-718](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-718)
Pending Unit Tests: [UTOPIA-1039](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1039)
Refer Swagger docs

[UTOPIA-533] [Backend] Comment entity and endpoints added - GET, POST, DELETE

---

src/backend/src/modules/comments/comments.controller.ts
src/backend/src/modules/comments/dto/find-comments.dto.ts

…
- updated find comments query params
- enforced class-validator validations
Swagger

[UTOPIA-533] [Backend] [FIX] updated find comments query params and enforced class-validator validations

---

src/frontend/src/pages/PIAForm/BannerStatus/messages.ts

[UTOPIA-1021] fix typo

---

src/frontend/nginx.conf

- [] Bug fix (non-breaking change which fixes an issue)

Update nigix CSP to allow snowplow

---

src/frontend/src/components/common/Collapsible/index.tsx
src/frontend/src/components/common/Navbar/index.tsx
src/frontend/src/hooks/useRovingTabIndex.tsx

- Fixed collapsible menu accessibility issues
Keyboard navigation

[UTOPIA-1036] Fixed collapsible menu accessibility issues

---

src/backend/src/modules/comments/comments.controller.ts
src/backend/src/modules/comments/comments.service.ts
src/backend/src/modules/comments/entities/comment.entity.ts
src/backend/src/modules/comments/enums/allowed-comment-paths.enum.ts
src/backend/src/modules/comments/ro/get-comment.ro.ts

- Bug fix: Find endpoint not filtering by pia-id - fixed

[UTOPIA-1055] Bug fix: Find endpoint not filtering by pia-id - fixed

---

src/frontend/src/pages/PiaFormPrintPreview/PrintHeader.tsx
src/frontend/src/pages/PiaFormPrintPreview/index.tsx

- updated print on image load
Print

[UTOPIA-1042] updated print on image load

---

src/backend/src/modules/comments/comments.controller.ts
src/backend/src/modules/comments/comments.service.ts
src/backend/src/modules/comments/dto/find-comments-count.dto.ts
src/backend/src/modules/comments/ro/comments-count-ro.ts

- added comments count endpoint

[UTOPIA-1057] added comments count endpoint

---

src/frontend/src/components/common/Collapsible/index.tsx
src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/components/public/CommentsSidebar/index.tsx
src/frontend/src/components/public/CommentsSidebar/interfaces.ts
src/frontend/src/constant/apiRoutes.ts
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/sass/_collapsible.scss
src/frontend/src/types/enums/pia-sections.enum.ts
src/frontend/src/utils/date.ts

- Minor adjustments to Collapsible component for accuracy of design
- Additional API_ROUTE for getting comment    
- Enum in frontend for allowable section paths
- Date formatting function for comments sidebar which also displays local time for hours and minutes
Used Swagger to add comments to section of PIA, then passed that section into the CommentSidebar component. Asserted that comments appear as intended.

UTOPIA-691: Implement Comment Sidebar UI

---

src/frontend/src/components/common/Collapsible/index.tsx
src/frontend/src/components/common/Collapsible/interfaces.ts
src/frontend/src/components/common/ViewComment/index.tsx
src/frontend/src/components/common/ViewComment/interfaces.ts
src/frontend/src/components/public/CommentsSidebar/index.tsx
src/frontend/src/components/public/CommentsSidebar/interfaces.ts
src/frontend/src/components/public/CommentsSidebar/messages.ts
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/components/public/PIAFormTabs/additionalRisks/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx
src/frontend/src/constant/apiRoutes.ts
src/frontend/src/contexts/PiaFormContext.ts
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/utils/http-request.util.ts

- Just share the progress of my work

[Utopia 691] add comments

---

src/backend/src/modules/auth/auth.controller.ts
src/backend/test/unit/auth/auth.controller.spec.ts
src/backend/test/unit/auth/auth.service.spec.ts
src/backend/test/unit/ppq/ppq.controller.spec.ts
src/backend/test/unit/ppq/ppq.service.spec.ts

[UTOPIA-1044]add more unit test for ppq and auth module and comments

---

src/frontend/src/components/public/CommentsSidebar/index.tsx
src/frontend/src/utils/date.ts

- render comments time at local time and format it

[UTOPIA-1064] fix comments time stamp format

---

src/backend/src/modules/comments/comments.controller.ts
src/backend/src/modules/comments/comments.service.ts
src/backend/test/unit/comments/comments.controller.spec.ts
src/backend/test/unit/comments/comments.service.spec.ts
src/backend/test/util/mocks/data/comments.mock.ts
src/backend/test/util/mocks/services/comments.service.mock.ts

- added test cases for the Comments module
npm run test:cov

[UTOPIA-1039] added test cases for the Comments module

---

src/frontend/src/components/common/Collapsible/index.tsx
src/frontend/src/components/common/Collapsible/interfaces.ts
src/frontend/src/components/common/ViewComment/index.tsx
src/frontend/src/components/public/CommentsSidebar/index.tsx
src/frontend/src/pages/PIAForm/index.tsx

[UTOPIA-1061]fix left and right collapsible show at same time issue

---

src/backend/src/modules/comments/enums/allowed-comment-paths.enum.ts
src/frontend/src/components/public/PIAFormTabs/intake/index.tsx
src/frontend/src/components/public/PIAFormTabs/intake/viewGeneralInformation.tsx
src/frontend/src/types/enums/pia-sections.enum.ts

- Added comments to PIA Intake

[UTOPIA-1062] Added comments to PIA Intake

---

src/frontend/cypress/e2e/login-page/loginpage.cy.ts

- UTOPIA-336 Update dev and Test environment URL checks

UTOPIA-336 Update dev and Test environment URL checks

---

src/frontend/src/components/common/Collapsible/index.tsx
src/frontend/src/components/common/Collapsible/interfaces.ts
src/frontend/src/components/public/CommentsSidebar/index.tsx
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/sass/_collapsible.scss
src/frontend/src/sass/_comment_sidebar.scss
src/frontend/src/sass/_default.scss
src/frontend/src/sass/common.scss

- Comment sidebar has own scroll context
- 'Add comment' UI is now positioned at the bottom of the comment
sidebar
Visual assertion.

UTOPIA-1065: Comment Sidebar Scroll & Add Comment UI Fix

---

src/frontend/src/components/common/ViewComment/index.tsx
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/sass/_buttons.scss
src/frontend/src/sass/_comment_sidebar.scss
src/frontend/src/sass/_default.scss

- The comments sidebar is now in a fixed position on the page
- Clicking 'View Comments' no longer causes a scroll to top
Visually.

UTOPIA-1065: Comments Sidebar UI Fixed Position

---

src/frontend/cypress.config.ts
src/frontend/cypress/e2e/login-page/loginpage.cy.ts

- UTOPIA-336 Correcting Log Out timeout issue

[UTOPIA-336] Correcting Log Out timeout issue

---

src/frontend/src/components/public/PIAFormTabs/additionalRisks/index.tsx
src/frontend/src/components/public/PIAFormTabs/additionalRisks/messages.ts

[UTOPIA-1022] add description text in addtional risk tab

---

src/frontend/src/components/public/PIAFormTabs/intake/helper/extract-intake-from-pia.helper.ts
src/frontend/src/components/public/PIAFormTabs/intake/index.tsx
src/frontend/src/components/public/PIAFormTabs/intake/pia-form-intake.interface.ts
src/frontend/src/components/public/PIAFormTabs/intake/viewGeneralInformation.tsx

[UTOPIA-765] remove drafter name/title/email from intake form

---

src/frontend/src/components/public/PIAFormTabs/intake/printPreview/index.tsx
src/frontend/src/components/public/PIAFormTabs/intake/viewGeneralInformation.tsx
src/frontend/src/pages/PiaFormPrintPreview/index.tsx

- update the pdf file to reflect the remove mpo related fields

[UTOPIA-951] update preview pdf after remove mpo fields

---

src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/messages.ts

…ment of disclosures outside of Canada section
- see title

[UTOPIA-1023] add call out to tab storing personal information Assessment of disclosures outside of Canada section

---

src/backend/src/common/interfaces/form-field.interface.ts
src/backend/src/common/validators/form-field-role.validator.ts
src/backend/src/migrations/1682963468806-ppq-tab-for-pia.ts
src/backend/src/modules/pia-intake/dto/create-pia-intake.dto.ts
src/backend/src/modules/pia-intake/entities/pia-intake.entity.ts
src/backend/src/modules/pia-intake/jsonb-classes/ppq/index.ts
src/backend/src/modules/pia-intake/mocks/create-pia-intake.mock.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts

**Adding an independent PPQ fields inside PIA; No relation to PPQ table already available.
Open to suggestions if anyone thinks we should leverage the Existing PPQ table.**
- Created PPQ jsonb column inside PIA
- redefined column structure with updated fields
- Added role check to allow changed only by MPOs
- Unit Tests

[UTOPIA-930]  [Backend] PPQ tab inside PIA 

---

src/frontend/src/components/public/PIAFormTabs/ppq/index.tsx
src/frontend/src/components/public/PIAFormTabs/ppq/interfaces.ts
src/frontend/src/components/public/PIAFormTabs/ppq/messages.ts
src/frontend/src/routes/router.tsx
src/frontend/src/types/interfaces/pia-form.interface.ts

- add new ppq tab for pia form
Edit mode
View mode

[Utopia 932] build ppq tab

---

src/frontend/src/components/public/PIANavButton/index.tsx
src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts
src/frontend/src/constant/routes.ts

- Conditional PPQ side nav link for MPOs
- Prev/next buttons changes dependent upon whether the user is an MPO or not
Changed role through Pathfinder SSO to check for conditional changes.

UTOPIA-1030: [FE] update next/back button navigation

---

src/frontend/src/components/public/PIAFormTabs/ppq/index.tsx
src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/components/public/StatusChangeDropDown/index.tsx
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/pages/PIAForm/messages.ts
src/frontend/src/utils/status.ts

[UTOPIA-960] allow user submit pia from mpo_review to pct_review

---

src/frontend/src/pages/PiaFormPrintPreview/index.tsx

[UTOPIA-1083] do not show ppq tab in delegate pia pdf

---

src/frontend/src/components/public/PIAFormTabs/ppq/interfaces.ts
src/frontend/src/components/public/PIAFormTabs/ppq/messages.ts
src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/components/public/PPQConnect/messages.ts
src/frontend/src/constant/constant.ts
src/frontend/src/pages/LandingPage/LandingPage.tsx
src/frontend/src/pages/PIAForm/BannerStatus/messages.ts
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/pages/PIAForm/messages.ts
src/frontend/src/pages/PPQFormPage/messages.ts
src/frontend/src/pages/PPQPage/messages.ts
src/frontend/src/pages/PiaFormPrintPreview/MessageSignatures.ts
src/frontend/src/sass/_statusBlock.scss
src/frontend/src/utils/status.ts

- Change all occurrences of PCT to CPO
- Change all occurrences of Privacy, Compliance and Training to Corporate Privacy Office
- Minor typo fixes 
N/a.

UTOPIA-1091: Update PCT name to CPO

---

src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/pages/PIAForm/index.tsx

- Disallows edit mode when pia status is CPO Review
- Removes Edit button from subheader if pia status is CPO Review
- Changed a PIA to CPO Review to assert correct behaviour
- Checked that PIAs in other statuses had unchanged behaviour

UTOPIA-1089: Remove Edit button when in CPO_Review

---

src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx

- allow the drafter to update filed Where are you storing the personal information involved in your initiative? in storing personal information tab

[UTOPIA-1014] allow drafter update field

---

src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx

- allow drafter update filed "Describe the contractual terms in place (if applicable)" in Storing personal information tab under  Assessment for Disclosure Outside Canada section

[UTOPIA-1077] allow drafter update field

---

src/frontend/src/sass/_font.scss

- Input area now using BCSans font family
- Preview now using BCSans font family
Visually asserted font family change to MDEditor component.

UTOPIA-948: Inconsistent font

---

src/frontend/src/components/public/StatusChangeDropDown/index.tsx
src/frontend/src/utils/helper.util.ts
src/frontend/src/utils/status.ts

- CPO role can change status: CPO Review ==> MPO Review
As CPO role, tested for correct status change behaviour based on JIRA ticket AC. MPO role was also tested to make sure that it couldn't behave as CPO.

UTOPIA-790: CPO changing PIA status

---

src/backend/src/app.config.ts

Update backend logs to include uuid

---

src/frontend/src/pages/PiaFormPrintPreview/index.tsx

- see title, increate time from 100ms to 500 ms

[UTOPIA-1058] increase time slot to generate pdf for pia

---

src/frontend/cypress/e2e/homepage/homepage.cy.ts

- [UTOPIA-1075] List of PIA page

[UTOPIA-1075] List of PIA page

---

src/frontend/src/sass/_statusBlock.scss
src/frontend/src/sass/_variables.scss

[UTOPIA-1108] make cpo-review status color change

---

src/frontend/src/components/public/PIASubHeader/index.tsx

[UTOPIA-1109] diable drafter can submit a pia in mpo-review status

---

src/frontend/src/utils/status.ts

- Corrects mistake where CPO Review was not added to all status' privilege arrays for MPOs
As an MPO role, moved PIAs from every status to CPO Review. 

UTOPIA-1103: Add 'CPO Review' to every status' privilege array for MPOs

---

src/frontend/src/pages/PIAForm/index.tsx

[UTOPIA-1112] when cpo change pia status, go back to pia list table

---

src/backend/src/modules/pia-intake/pia-intake.service.ts

- the 403 error casued by backend access validation check, add MPO_REVIEW status to cpo role, which allow the cpo to update pia status back to mpo_review

[UTOPIA-1112] fix cpo update pia status throw 403 error

---

src/frontend/src/pages/PiaFormPrintPreview/PrintHeader.tsx
src/frontend/src/pages/PiaFormPrintPreview/index.tsx

- new implementation to fix pdf missing filed value issue

[UTOPIA-1058]new-way-fix-pdf-missing-fields

---

src/frontend/src/components/public/PIAFormTabs/intake/printPreview/intakedetails.tsx

[[UTOPIA-1098] fix the pia intake print format lost issue

---

src/frontend/src/components/public/PIAFormTabs/intake/printPreview/intakedetails.tsx

- render last field in pia intake to md

[UTOPIA-1098] fix pdf intake print format for scope field

---

src/backend/src/app.config.ts

Add idir and roles to the logs

---

src/backend/src/app.config.ts
src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/components/public/StatusChangeDropDown/index.tsx
src/frontend/src/utils/helper.util.ts
src/frontend/src/utils/status.ts

- Changes status state machine
- Modal content now comes from a role's privileges
- Status dropdown list fix
- Conditional modal content  

UTOPIA-1113: Modal not updated

---

src/backend/src/common/helpers/base-helper.ts
src/backend/test/util/mocks/data/comments.mock.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts
src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/hooks/userFetchKeycloakUserInfo.tsx
src/frontend/src/types/interfaces/keyCloakToken.interface.ts
src/frontend/src/types/interfaces/keycloakUserInfo.interface.ts
src/frontend/src/types/interfaces/pia-form.interface.ts
src/frontend/src/utils/auth.ts
src/frontend/src/utils/helper.util.ts
src/frontend/src/utils/status.ts

- Fix missing submit button bug 

add submit logic and guid

---

src/frontend/src/components/public/CommentsSidebar/index.tsx
src/frontend/src/components/public/CommentsSidebar/interfaces.ts

- previous to check comment author we are using user login name, but this looks cause some user can not delete their own comment, now use uuid to check the owner of a comment

[UTOPIA-1099] use uuid to check comment author instead of user login name

---

src/frontend/src/utils/status.ts

- CPO privileges for all statuses
As a CPO, used the status dropdown to switch between statuses.

UTOPIA-1114: CPO can't draft and submit a PIA

---

src/frontend/src/components/common/SearchBox/index.tsx

- fix accessibility issue for list of pia page search icon buttn

[UTOPIA-989] add aria-label for list page search icon btn

---

src/frontend/src/pages/PIAForm/BannerStatus/index.tsx
src/frontend/src/pages/PIAForm/BannerStatus/messages.ts
src/frontend/src/utils/status.ts

[UTOPIA-1002]add banner info for cpo_review status

---

src/frontend/src/components/public/PIAListTable/TableOrdering.tsx
src/frontend/src/components/public/PIAListTable/index.tsx

[UTOPIA-990] fix table sort by accessibility issue

---

src/frontend/src/components/public/PIAIntakeFilter/index.tsx

[UTOPIA-1150] make cpo and mpo both can see full filter options

---

src/frontend/src/components/common/Pagination/button.tsx
src/frontend/src/components/common/Pagination/listPageNumber.tsx
src/frontend/src/components/common/Pagination/rowsPerPage.tsx

- add Accessibility fix for table view pagination 

[Utopia 993/1004] pagination accessibility fix

---

src/frontend/src/components/public/StatusChangeDropDown/index.tsx

Update duplicate status changes

---

src/frontend/src/components/public/PIAListTable/index.tsx

[UTOPIA-1007] add accessibility support for table

---

src/frontend/index.html
src/frontend/src/components/common/Collapsible/index.tsx
src/frontend/src/components/common/Dropdown/index.tsx
src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/components/common/Modal/index.tsx
src/frontend/src/components/common/SearchBox/index.tsx
src/frontend/src/components/common/Table/views/useTableRowView.tsx
src/frontend/src/components/common/Table/views/useTableStandardView.tsx
src/frontend/src/components/public/CommentsSidebar/index.tsx
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx
src/frontend/src/components/public/PIAFormTabs/intake/index.tsx
src/frontend/src/components/public/PIAFormTabs/ppq/index.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx
src/frontend/src/components/public/PIANavButton/index.tsx
src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/components/public/StatusChangeDropDown/index.tsx
src/frontend/src/sass/_form.scss

- Add accessibility labels to form elements

UTOPIA-1032: Missing labels for form elements, filters, searches, and buttons

---

src/frontend/src/components/common/Pagination/listPageNumber.tsx

[UTOPIA-993] fix typo

---

src/backend/src/modules/auth/auth.controller.ts

- Make logout protected endpoint
N/A

[UTOPIA-595] removed unprotected from the logout endpoint

---

src/frontend/test/specs/e2e/CreatePIA.spec.js
src/frontend/wdio.conf.js

… error
-  Automate more scenarios to Full PIA 
- Fix Math.Random error

[UTOPIA-1127] Automate more scenarios to Full PIA and fix math.random

---

src/frontend/src/components/public/PIAListTable/index.tsx
src/frontend/src/sass/_table.scss

- adjusted aria labels for pia list table
Using Sceen Reader

[UTOPIA-1007] adjusted aria labels for pia list table

---

src/frontend/src/pages/PIAForm/index.tsx

- only the very first time( create a new PIA) will route URL to intake/edit 
- all the other scenarios will keep the URL unchanged so the user can continue work on the same tab/page

[UTOPIA-1013] make sure the auto save not route url to intake tab  after create the pia

---

src/frontend/src/pages/LandingPage/LandingPage.scss
src/frontend/src/sass/_variables.scss

Utopia 991

---

src/frontend/src/components/public/PIAListTable/TableOrdering.tsx
src/frontend/src/components/public/PIAListTable/index.tsx

[Utopia-990]  make sort icon keyboard access

---

src/frontend/src/pages/PIAForm/index.tsx

[UTOPIA-1056] make left sidebar default open

---

src/backend/package-lock.json

- yaml - high vulnerability fix

yaml - high vulnerability fix

---

src/frontend/src/routes/router.tsx

- Unauth'd navigation redirects to NotAuthorized page 
While logged out, attempted to navigate to a known URL via the browser address bar.

UTOPIA-690: No 401 Error Page

---

src/frontend/src/components/common/Dropdown/interfaces.ts
src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/routes/router.tsx
src/frontend/src/utils/auth.ts

Recreated this PR with a new branch because the commit history was messed up.
- Uses AppStorage to store pasted URL in key: 'returnUri'
- Logout due to inactivity also stores the last location
- Provides fallback to '/pia/list'
- Slightly refactors Header.tsx auth useEffect callback function
- Pasted in known URLs that were not the PIA list page
- Logged in normally (without pasting in a link), fallback worked as expected

UTOPIA-837: Login should return to PIA link if id is provided

---

src/frontend/src/components/common/Unauthorized/index.tsx

- Login button now on Unauthorized page
- 'Go to Home' button clears the 'returnUri' from AppStorage
Pasted in link and tried both button functionalities.

UTOPIA-837: Unauthorized page flow

---

src/backend/src/common/validators/form-field-role.validator.ts
src/backend/src/migrations/1686769976593-pia-review-jsonb-column.ts
src/backend/src/modules/pia-intake/dto/create-pia-intake.dto.ts
src/backend/src/modules/pia-intake/entities/pia-intake.entity.ts
src/backend/src/modules/pia-intake/jsonb-classes/collection-use-and-disclosure/collection-notice.ts
src/backend/src/modules/pia-intake/jsonb-classes/collection-use-and-disclosure/index.ts
src/backend/src/modules/pia-intake/jsonb-classes/collection-use-and-disclosure/steps-walkthrough.ts
src/backend/src/modules/pia-intake/jsonb-classes/ppq/index.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/index.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/mpo-review.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/program-area-review.ts
src/backend/src/modules/pia-intake/mocks/create-pia-intake.mock.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts

- Review Entity
- Roles consideration
- Test cases
Test cases

[UTOPIA-1153] add review column in the PIA entity + roles + test cases

---

openshift/templates/api/emerald/api-dc-template.yaml

Changing image pull policy on API template to test change in tekton pipeline

UTOPIA-782: Changing Image Pull Policy for Emerald Deployment

---

src/backend/src/modules/pia-intake/jsonb-classes/review/mpo-review.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts

- added review submission fields

[UTOPIA-1153] adding review submission fields

---

src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/components/common/Modal/index.tsx
src/frontend/src/components/public/PIASubHeader/messages.ts

- Amends access link modal body copy
- Implements an 'onFocus' select for the access link so that it is selected with a single click
- making readOnly, instead of disabling, and not using the existing readOnly prop here because of the other behaviours tied to that prop
- Visual assertion for copy change
- Single click on access link for new selection behaviour

UTOPIA-838: Amend copy & link selection

---

src/frontend/src/components/common/Checkbox/index.tsx
src/frontend/src/components/common/Navbar/interfaces.ts
src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/interfaces.ts
src/frontend/src/components/public/PIAFormTabs/review/messages.ts
src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts
src/frontend/src/constant/constant.ts
src/frontend/src/constant/routes.ts
src/frontend/src/routes/router.tsx
src/frontend/src/sass/_buttons.scss
src/frontend/src/types/interfaces/pia-form.interface.ts

Utopia 1152

---

.github/helpers/trigger-tekton.sh

creating helper script to trigger tekton event listener url

UTOPIA-782: creating helper script to trigger tekton event listener url

---

src/backend/src/modules/pia-intake/enums/pia-intake-status.enum.ts
src/backend/src/modules/pia-intake/helper/handle-pia-status-change.ts
src/backend/src/modules/pia-intake/helper/handle-pia-updates.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/program-area-review.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/programArea/programAreaSelectedRoleReviews.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/role-review.ts
src/backend/src/modules/pia-intake/metadata/pia-status.metadata.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts

- [UTOPIA-1180 (backend) update review fields for program area](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1180)
- [UTOPIA-1182 (backend) restrict changes once in complete status](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1182)

[UTOPIA-1078] [UTOPIA-1180] [UTOPIA-1182] review fields added for program area reviews + COMPLETE status

---

src/frontend/test/features/featurefiles/e2e/UTOPIA-584_SearchSortFilter.feature
src/frontend/test/features/pageobjects/page.js
src/frontend/test/features/pageobjects/searchsortfilter.page.js
src/frontend/test/features/step-definitions/SearchSortFilter.js

- Automate Sort functionality with validation

UTOPIA-1231 Update Sort functionality with validation

---

src/backend/src/modules/pia-intake/pia-intake.service.ts
src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/interfaces.ts
src/frontend/src/components/public/PIAFormTabs/review/viewMPOReview.tsx
src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/pages/PIAForm/index.tsx

- complete mpo review ui for delegate PIA
final review status hide the edit review button
MPO review status can see the edit button.

[UTOPIA-1152] update mpo review section ui

---

src/backend/src/modules/pia-intake/helper/handle-pia-updates.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/handle-pia-updates.spec.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

- pia-intake.service test cases updated
- helper method test case for handle-pia-updates
Test cases

[UTOPIA-1078] Test cases for pia-intake.service.ts

---

src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/interfaces.ts

- Implements 'view' rendering in Final Review for 'Selected Roles' section 
Visual.

UTOPIA-1237: Create Missing UI

---

src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/interfaces.ts
src/frontend/src/components/public/PIAFormTabs/review/pendingReview.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewMPOReview.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewProgramArea.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewReviewSection.tsx
src/frontend/src/pages/PiaFormPrintPreview/index.tsx
src/frontend/src/sass/_printPreview.scss

[Utopia 1185] add review pdf

---

src/frontend/src/components/public/PIAFormTabs/review/viewMPOReview.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewProgramArea.tsx

- in dev the edit review button disappear
this is the correct 

[UTOPIA-1185] fix edit review button disappear issue

---

src/frontend/src/components/public/PIAFormTabs/review/index.tsx

[UTOPIA-1256] add space for required text and review note

---

src/frontend/src/components/public/PIAFormTabs/review/viewReviewSection.tsx

- change text from Date received to Date reviewed

[UTOPIA-1259] update word

---

src/frontend/src/pages/PPQFormPage/PPQFormPage.scss

Update checkbox alignement

---

src/frontend/src/utils/status.ts

Utopia 1254 - Info banner still present

---

.github/workflows/emerald-build-push-api.yaml
.github/workflows/emerald-build-push-app.yaml

UTOPIA-782: Modifying Emerald Git Actions to Accomodate Tekton Deployment Triggers

---

.github/workflows/emerald-build-push-api.yaml

Fixing naming of script used to trigger tekton pipelines

UTOPIA-782: Typo

---

src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts

Disable review tab for PI till PI review is completed

---

.github/workflows/emerald-build-push-api.yaml

Removing github environment secret from tekton trigger parameters

UTOPIA-782: Removing Secret from Tekton Trigger

---

src/frontend/src/components/public/PIAFormTabs/review/index.tsx

click clear will remove review note and  uncheck the checkbox

---

.github/helpers/trigger-tekton.sh

Changing parameter passed to helper script

UTOPIA-782: Incorrect Parameter

---

src/frontend/src/components/public/PIAFormTabs/review/index.tsx

[UTOPIA-1257] update the implementation for clear button for mpo review

---

.github/helpers/trigger-tekton.sh
.github/workflows/emerald-build-push-api.yaml

UTOPIA-782: Adding Correct Syntax for Environment Variable 

---

.github/helpers/trigger-tekton.sh

removing quotes causing illegal curl URL error

UTOPIA-782: Curl Typo

---

src/frontend/src/pages/PIAListPage/index.tsx

utopia-1135 - Reset search query to page 1 when searching

---

.github/workflows/app-e2e.yaml
.github/workflows/tag-deploy-app-test.yaml
src/frontend/test/features/featurefiles/e2e/UTOPIA-584_SearchSortFilter.feature
src/frontend/test/features/pageobjects/authenticated.page.js
src/frontend/test/features/pageobjects/login.page.js
src/frontend/test/features/pageobjects/page.js
src/frontend/wdio.conf.js

- Fix existing errors on Auth and Unauth features

UTOPIA-1205 Fix existing errors on auth and unauth features

---

src/frontend/src/components/public/PIAIntakeFilter/index.tsx
src/frontend/src/components/public/PIAIntakeFilter/interfaces.ts
src/frontend/src/pages/PIAListPage/index.tsx

Utopia-1132 Reset page number when changing search filters

---

src/frontend/src/constant/constant.ts

Utopia-992 fix Underscores in status dropdown filter

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/helper/messages.ts
src/frontend/src/components/public/PIAFormTabs/Next_Steps/nextStepsDelegatedFlow.tsx

Utopia-1031 Missing external link on Next Steps

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/helper/messages.ts
src/frontend/src/components/public/PIAFormTabs/Next_Steps/nextStepsDelegatedFlow.tsx

Utopia-1031 Added external link icon

---

src/frontend/src/components/common/Checkbox/_checkbox.scss
src/frontend/src/components/public/PIAFormTabs/review/editProgramArea.tsx
src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/interfaces.ts
src/frontend/src/components/public/PIAFormTabs/review/messages.ts
src/frontend/src/components/public/PIAFormTabs/review/viewMPOReview.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewProgramArea.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewReviewSection.tsx
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/sass/_default.scss
src/frontend/src/utils/object-modification.util.ts

- Program Area can accept accountability and review PIAs

UTOPIA-1181: (frontend) create missing UI

---

src/frontend/src/components/public/PIAIntakeFilter/index.tsx
src/frontend/src/components/public/PIAIntakeFilter/interfaces.ts
src/frontend/src/pages/PIAListPage/index.tsx

Utopia-1134 Filter labels do not reset when list page link clicked

---

src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts
src/frontend/src/utils/status.ts

- update review tab MPO review section for PI PIA. allow MPO to accept accountability in PI PIA
- the review note is optional for MPO 

[UTOPIA-1174] update review tab for pi pia

---

src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/utils/path.ts

Utopia-1279 - Fix edit link issues when in review tab

---

src/backend/src/modules/pia-intake/metadata/pia-status.metadata.ts

Due to the change in the Product direction, allowing changing status of a DELEGATED PIA from MPO_REVIEW to CPO_REVIEW

[BACKEND] allow changing status of a DELEGATED PIA from MPO_REVIEW to CPO_REVIEW

---

src/backend/src/common/enums/size.enum.ts
src/backend/src/common/helpers/get-nested-helper.ts
src/backend/src/modules/pia-intake/helper/check-field-validations.ts
src/backend/src/modules/pia-intake/helper/handle-pia-status-change.ts
src/backend/src/modules/pia-intake/helper/handle-pia-updates.ts
src/backend/src/modules/pia-intake/helper/validate-conditions.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/mpo-review.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/role-review.ts
src/backend/src/modules/pia-intake/metadata/pia-status.metadata.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/handle-pia-updates.spec.ts

[UTOPIA-1168] and Status changes for PI PIA / CPO

---

src/backend/src/modules/pia-intake/metadata/pia-status.metadata.ts

- Allow Final Review to Complete Status movement
- Delete review when moving to Edit or incomplete status

[UTOPIA-1283-be] Allow complete status + delete review when moving to Edit or incomplete status

---

src/frontend/src/components/public/PIAFormTabs/review/editProgramArea.tsx
src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewReviewSection.tsx
src/frontend/src/components/public/PIANavButton/handleState.tsx
src/frontend/src/utils/object-comparison.util.ts

- allow the user to clear their review for program area

[Utopia 1287] implement program area clear button function 

---

src/frontend/src/components/public/StatusChangeDropDown/populateModal.tsx
src/frontend/src/utils/status.ts

[UTOPIA-1280]fix drafter can not click edit button in mpo_review status

---

openshift/templates/api/silver/api-dc-template.yaml

Adding ClamAV config to API to allow for consumption locally

UTOPIA-1297: Adding ClamAV Config to API template

---

src/frontend/src/pages/PIAForm/index.tsx

fix the broken routes

---

src/frontend/src/components/public/PIAFormTabs/review/index.tsx

- last rebase I made a mistake, lost the 1288 main fix code. this pr just add the code 

rebase lost the 1288 code and added back to fix the issue

---

src/frontend/src/components/public/PIAFormTabs/review/accessControl.tsx
src/frontend/src/components/public/PIANavButton/index.tsx
src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts
src/frontend/src/utils/status.ts

Added access control for the review page side nav and bottom nav

---

src/frontend/test/features/featurefiles/e2e/UTOPIA-1121_Drafter_ViewPIA.feature
src/frontend/test/features/featurefiles/e2e/UTOPIA-1122_CPO_ViewPIA.feature
src/frontend/test/features/featurefiles/e2e/UTOPIA-535_SubmitPIA.feature
src/frontend/test/features/featurefiles/e2e/UTOPIA-566_CreatePIA.feature
src/frontend/test/features/featurefiles/e2e/UTOPIA-591_SearchSortFilterMPO_CPO.feature
src/frontend/test/features/featurefiles/e2e/UTOPIA-617_FillPIA.feature
src/frontend/test/features/featurefiles/e2e/UTOPIA-631_MPO_ViewPIA.feature
src/frontend/test/features/featurefiles/e2e/UTOPIA-711_AutoSave.feature
src/frontend/test/features/pageobjects/createPIA.page.js
src/frontend/test/features/pageobjects/page.js
src/frontend/test/features/pageobjects/searchsortfilter.page.js
src/frontend/test/features/pageobjects/submitPIA.page.js
src/frontend/test/features/step-definitions/CreatePIA.js
src/frontend/test/features/step-definitions/Loginsteps.js
src/frontend/test/features/step-definitions/SubmitPIA.js

- UTOPIA-1296 Fill out PPQ UTOPIA-616
- UTOPIA-1121_Drafter_ViewPIA
- UTOPIA-535_SubmitPIA
- UTOPIA-566_CreatePIA

UTOPIA-1296 Fill out PPQ UTOPIA-616

---

src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/utils/status.ts

Utopia 1286

---

src/frontend/src/components/public/PIAIntakeFilter/index.tsx
src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts
src/frontend/src/utils/helper.util.ts

[UTOPIA-1289] fix cpo user can not see ppq tab

---

src/frontend/test/features/featurefiles/e2e/UTOPIA-1121_Drafter_ViewPIA.feature
src/frontend/test/features/featurefiles/e2e/UTOPIA-1122_CPO_ViewPIA.feature
src/frontend/test/features/featurefiles/e2e/UTOPIA-617_FillPIA.feature
src/frontend/test/features/featurefiles/e2e/UTOPIA-631_MPO_ViewPIA.feature
src/frontend/test/features/featurefiles/e2e/home.feature
src/frontend/test/features/pageobjects/login.page.js
src/frontend/test/features/pageobjects/searchsortfilter.page.js

- Fix the latest change on Active PIAs

UTOPIA-1323 Fix the latest change on Active PIAs

---

src/frontend/src/components/public/PIAFormTabs/intake/helper/messages.ts
src/frontend/src/components/public/PIAFormTabs/intake/index.tsx

- Change "Before you begin" text on PIA Intake Page
Visual assertion.

UTOPIA-1097: Update "Before you begin" text

---

src/frontend/package-lock.json
src/frontend/package.json

- UTOPIA-1325 Update chrome browser service package

UTOPIA-1325 Update chrome browser service package

---

src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

- CPO can now see all COMPLETEd PIAs along with CPO_REVIEW
Locally tested.

[UTOPIA-1332] CPO can now see all COMPLETEd PIAs along with CPO_REVIEW

---

.github/CODEOWNERS
.github/auto-action-config.yaml

- Adding Brady, Noor, Sarah to the repository
-_-
NEW DEVS introduced that will drastically reduce code complexity over the long run :D

[UTOPIA-1344] Adding Brady, Noor, Sarah to the repository

---

.gitattributes
src/backend/.prettierrc
src/frontend/.prettierrc

- Updated git attributes so all new files will be converted to eol=CRLF (exception for .sh files).
- Added endOfLine CRLF to prettier configs.
Re-opening VSCode showed the errors from prettier had gone away.

[UTOPIA-1343] Updated eol configs

---

openshift/templates/api/silver/api-dc-template.yaml

Adding config values for s3 bucket connection to API DC template.

UTOPIA-1305: Adding S3 Config to API DC template

---

.gitattributes
src/backend/.prettierrc
src/frontend/.prettierrc

- Changed eol configs to LF as CRLF was a mistake.

Fixed eol configs

---

src/frontend/src/constant/constant.ts

[UTOPIA-1304](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1304) Filter by status is missing some statuses
* Added Final Review and pending completion status on the dropdown of the List of PIA page
* **Waiting for the pending completion implementation([UTOPIA-1234](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1234))** 
Visually, the filter works.

[UTOPIA-1304] add missing filter status

---

src/frontend/src/utils/status.ts

[UTOPIA-1356](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1356) MPO can move Final Review to Complete without all reviews done
* Removed Complete status on the dropdown in Final Review
Visually, the dropdown works.

[UTOPIA-1356] Remove Complete status

---

src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/components/public/StatusChangeDropDown/index.tsx
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/utils/status.ts

- Submit button render handled in state machine for users with roles
- 'DRAFTER' role implementation
- New 'UserRole' type (MPO | CPO | DRAFTER)

UTOPIA-1307 (update): Update state machine for submit button 

---

src/frontend/src/utils/status.ts

- [UTOPIA-1163](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1163) Added MPO review status for incomplete PIA dropdown

[UTOPIA-1163] add MPO review status for incomplete PIA

---

.github/CODEOWNERS

- EY devs and QA removed from CODEOWNERS file
N/A.

Remove EY from CODEOWNERS.

---

.github/PULL_REQUEST_TEMPLATE.md

- Fixed typo in PR template
Refactor of pr template so no testing done

[UTOPIA-1388] Fix typo in PR template

---

src/backend/src/modules/pia-intake/jsonb-classes/ppq/index.ts

- add new required ppq fields 
using existing tests

[UTOPIA-1248] (backend) create required PPQ fields

---

src/frontend/src/components/common/Checkbox/_checkbox.scss
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/sass/_form.scss

- utilized Radio component to render radio buttons in forms
- forced font weight and margin top to radio buttons
- made checkboxes same color as radio buttons for consistency
locally tested

[UTOPIA-982] - 2 different UI styles for radio buttons

---

src/backend/src/modules/comments/comments.service.ts
src/frontend/src/components/public/CommentsSidebar/index.tsx

- Recreated the PR template again because of the eslint issue.
- [UTOPIA-1196](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1196) disabled add button for all empty comment
- [UTOPIA-1197](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1197) validate empty text and throws exception

[UTOPIA-1116] disable add button on empty comment

---

src/backend/src/common/validators/form-field-role.validator.ts
src/frontend/src/components/public/PIAFormTabs/review/index.tsx

[UTOPIA-791](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-791): CPO Adding a Review Note On a PI PIA
- Resolves: User can not edit initial CPO review without auto-save error.
- Resolves: User can not clear review without page going blank.
DOES NOT INCLUDE fix for "Add Reviewer" button not showing up.
Tested clearing and editing reviews.

[UTOPIA-1399] Resolve CPO Review Issues

---

src/backend/.config/.env.local
src/backend/src/config/config.service.ts
src/backend/src/modules/auth/auth.controller.ts
src/backend/src/modules/auth/auth.service.ts
src/backend/src/modules/auth/keycloack-token.model.ts
src/backend/test/unit/auth/auth.controller.spec.ts
src/backend/test/unit/auth/auth.service.spec.ts
src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/components/common/Unauthorized/index.tsx
src/frontend/src/constant/apiRoutes.ts
src/frontend/src/routes/router.tsx
src/frontend/src/types/interfaces/keyCloakToken.interface.ts
src/frontend/src/utils/auth.ts

This does not resolve the issue of login/logout.
Marco from SSO team needs this in dev to test.

Improved logout implementation

---

src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewCPOReview.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewProgramArea.tsx
src/frontend/src/components/public/PIASubHeader/index.tsx

https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1399
- Fixes the blank screen when clearing a CPO review.
Clearing the review works.

[UTOPIA-1399] Fix clear review

---

src/frontend/src/components/public/PIAFormTabs/accuracyRetention/accuracy-retention-interface.ts
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/components/public/PIAFormTabs/additionalRisks/AdditionalRisks.ts
src/frontend/src/components/public/PIAFormTabs/additionalRisks/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/AgreementsAndInformationBanks.ts
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/CollectionUseAndDisclosure.ts
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewCPOReview.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewMPOReview.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewProgramArea.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/security-personal-info-interface.ts
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/interfaces.ts
src/frontend/src/pages/PiaFormPrintPreview/index.tsx
src/frontend/src/routes/router.tsx

- [UTOPIA-1262](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1262) Show review section in PDF for full pia
- Changed duplicated style conflict issue
- Hide comments button in PDF

[UTOPIA-1262] Review Section missing in PDF

---

src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/utils/statusList/types.ts

- Missed commit during UTOPIA-1408 changing edit review permissions.

Missed from UTOPIA-1408

---

.github/helpers/check-npm-dependencies.js
.github/helpers/github-api/create-and-close-existing-issue.js
.github/helpers/github-api/github-api-requests.js
.github/workflows/api-npm-dep-check.yaml
.github/workflows/app-npm-dep-check.yaml

https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1413
- Added workflows and helpers for App and API dependency reporters.
- Reports once a week on Tuesday morning, or when manually triggered.
Will be tested once merged.

[UTOPIA-1413] Added dependency reporter workflows

---

src/frontend/package-lock.json
src/frontend/package.json

[Jira Ticket](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1414)
[GitHub Issue](https://github.com/bcgov/cirmo-dpia/issues/1521)
Tested each dependency individually before next commit.

[UTOPIA-1414] Update frontend minor production dependencies

---

.github/helpers/check-npm-dependencies.js

- Small change - added checkbox.

Added check box to dependency reporter

---

src/frontend/src/components/public/PIAFormTabs/review/ProgamArea/displayProgramArea.tsx
src/frontend/src/components/public/PIAFormTabs/review/ProgamArea/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/pages/PIAForm/index.tsx

- refactor addRole function
- create deleteRole function 
Locally tested

[UTOPIA 1410] - (Frontend) Add multiple program area reviewers

---

src/frontend/src/components/public/PIAFormTabs/review/ProgamArea/displayProgramArea.tsx
src/frontend/src/components/public/PIAFormTabs/review/index.tsx

https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-791
- Fixes autosave error when CPO user edits program area (add/delete), and CPO is a different user than MPO. It was erroring because mpo review data was not being passed to the backend and it thought the user was trying to delete mpo review.

[UTOPIA-1410] Fix autosave error

---

src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1394
https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1398
- CPOs can now view Final Review status

[UTOPIA-1394 & UTOPIA-1398] PIA statuses not visible to CPO

---

.github/workflows/app-lint.yaml

- [UTOPIA-1424](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1424) typo change

[UTOPIA-1424] Fixed frontend lint typo 

---

src/frontend/test/features/featurefiles/e2e/MPO_ViewPIA.feature
src/frontend/test/features/pageobjects/submitPIA.page.js

- [UTOPIA-1403](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1403)
- Changed checkbox selector with label
- Added edit review step

[UTOPIA-1403] MPO Review E2E

---

src/frontend/wdio.conf.js

- Fixed dev e2e sanity test run

Fixed dev e2e sanity test run

---

src/backend/package-lock.json
src/backend/package.json

[GitHub Issue](https://github.com/bcgov/cirmo-dpia/issues/1537)
[Jira Ticket](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1419)
Tested each package individually by rebuilding the backend.

[UTOPIA-1419] (Backend) Update patch production dependencies

---

src/backend/package-lock.json
src/backend/package.json

[GitHub Issue](https://github.com/bcgov/cirmo-dpia/issues/1537)
[Jira Ticket](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1421)
Tested each package individually by rebuilding the backend.

[UTOPIA-1421] (Backend) Update patch dev dependencies

---

src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewCPOReview.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewMPOReview.tsx

- removed extra title headers for CPO and MPO reviewers
- removed style breaking classnames
- removed unnecessary functions and consolidated into smaller more succinct function
- removed extra imports
- added better code comments to describe what functions do and why
locally tested

[UTOPIA-1400] (Frontend) Add multiple reviewers

---

.github/workflows/app-e2e.yaml

https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1447
- Added inputs for environment, suite and optionally feature file.
Requires testing once merged.

[UTOPIA-1447] Updated e2e workflow for easier testing

---

.github/workflows/app-e2e.yaml
src/frontend/package.json
src/frontend/wdio.conf.js

- Changed echo WDIO_CMD into its own step.
- Changed environment input to limit to APP-Dev and APP-Test
- Reverted directory change.
- Removed unused acceptance suite.

[UTOPIA-1447] Edited app-e2e

---

.github/workflows/app-e2e.yaml
src/frontend/wdio.conf.js

- Now only copies src/frontend and root level files on checkout.
- Properly handles feature file input.
- Properly creates npm run wdio command.
- Added config to bail on first failed test.
Tested in forked repo github actions.

[UTOPIA-1447] Fixed e2e test run workflow

---

src/frontend/src/pages/PIAForm/index.tsx

[UTOPIA-1405: Snowplow - Track data](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1405)
- Sends call to snowplow when pia is first created with an id.
- Sends call to snowplow when status is completed 
(Moving from Edit_In_Progress to MPO_Review is `EDIT_IN_PROGRESS-COMPLETED`)
- Sends call to snowplow when in a new status.
- Fixed next steps not updating backend state on status change (only updated local state).
---
`Tested with Snowplow chrome extension.`
---

[UTOPIA-1407] Track state change in snowplow

---

src/frontend/src/components/public/PIAFormTabs/review/ProgamArea/displayProgramArea.tsx

- [UTOPIA-1395](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1395)
- Fixed logic on viewMode function

[UTOPIA-1395] Selected program area roles not visible when partially signed in Final Review

---

src/frontend/src/components/public/PIAFormTabs/review/viewProgramArea.tsx

- [UTOPIA-1430](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1430)
- Changed it to data from the Program Area instead of fetching MPO information.

[UTOPIA-1430] Program area review displays incorrect information

---

src/frontend/src/components/public/PIAFormTabs/review/viewProgramArea.tsx

[UTOPIA-1416](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1416)
- Fixed edit button not showing on program area review.
Tested edit review in final review. Does not show in mpo review or cpo review as expected.

[UTOPIA-1416] Ministry designate cannot edit/clear their review

---

src/frontend/src/pages/PIAActiveListPage/index.tsx
src/frontend/test/features/pageobjects/login.page.js

[UTOPIA-1392](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1392)
- Fixed typo.

[UTOPIA-1392] Typo on Active PIAs and Completed PIAs lists

---

src/frontend/package-lock.json
src/frontend/package.json

- [UTOPIA-1465](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1465)
- [Github issues](https://github.com/bcgov/cirmo-dpia/issues/1569)
- Updated minor prod dependencies 

[UTOPIA-1465] (Frontend) Update minor prod dependencies 

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/nextStepsPI.tsx

[UTOPIA-1431](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1431)
- Changed status change from edit in progress to mpo review.

[UTOPIA-1431] Share with MPO button after creating a PIA does not change status to MPO review

---

src/frontend/src/components/public/PIAFormTabs/review/viewCPOReview.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewMPOReview.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewProgramArea.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewReviewSection.tsx

[UTOPIA-1428](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1428)
- Fixed issue where mpo review would go into edit mode after making changes on another part of the review page.
- Fixed role title not being visible on program area review notes.
Tested happy flow from MPO_REVIEW to FINAL_REVIEW

[UTOPIA-1428] Adding Role in Program Area Made Review Section Non-Editable

---

src/frontend/package-lock.json
src/frontend/package.json

- [UTOPIA-1465](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1465)
- [Github issues](https://github.com/bcgov/cirmo-dpia/issues/1569)
- Updated patch dev dependencies 

[UTOPIA-1465] (Frontend) Update patch dev dependencies

---

src/frontend/package-lock.json
src/frontend/package.json

- [UTOPIA-1465](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1465)
- [Github issues](https://github.com/bcgov/cirmo-dpia/issues/1569)
- Updated minor dev dependencies 

[UTOPIA-1465] (Frontend) Update minor dev dependencies

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/helper/messages.ts

[UTOPIA-1426](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1426)
- Changed wording "Submit to MPO" on next steps.

[UTOPIA-1426] Update wording on Next Steps page

---

src/frontend/src/components/public/PIAFormTabs/intake/index.tsx
src/frontend/test/features/pageobjects/submitPIA.page.js

[UTOPIA-1301](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1301)
- Changed wording of Title on Pia Intake.

[UTOPIA-1301] Changed wording of Title on Pia Intake

---

src/backend/src/modules/pia-intake/jsonb-classes/ppq/index.ts
src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/components/public/PIAFormTabs/ppq/index.tsx
src/frontend/src/components/public/PIAFormTabs/ppq/interfaces.ts
src/frontend/src/components/public/PIAFormTabs/ppq/messages.ts
src/frontend/src/pages/PPQFormPage/PPQFormPage.scss

- [UTOPIA-1249](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1249)
- create new UI components for related enactment and operational PIAs
- add ability to add and delete related enactment and operational PIAs
- add Initiative Summary component with character count
- add code comments for improved readability
locally tested

[UTOPIA-1249] - (frontend) update UI to add questions

---

src/frontend/src/utils/auth.ts

[UTOPIA-1470](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1470)
- Changed login redirect to only happen when entering a url from before login, so it wont redirect back to the previous page you were on before logout.

[UTOPIA-1470] New log in returns me to the last PIA I was looking at

---

src/frontend/src/pages/PIAForm/index.tsx

[UTOPIA-980](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-980)
- Fixed not working on edit_in_progress and incomplete

[UTOPIA-980] Fix edit redirect tab

---

src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/components/public/StatusChangeDropDown/_statuschangedropdown.scss
src/frontend/src/components/public/StatusChangeDropDown/index.tsx
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/sass/common.scss

[UTOPIA-1038](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1038)
- Dropdown is accessible by "Tab" / "Shift + Tab", then "Enter" or "Down".
- Dropdown statuses are navigable by "Down", "Right" or "Up" and "Left" arrows. 

[UTOPIA-1038] Change status dropdown no longer keyboard accessible

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1466](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1466)
[GitHub Issue](https://github.com/bcgov/cirmo-dpia/issues/1603)
- Omitted wdio package updates.

[UTOPIA-1466] Frontend patch/minor dependency updates

---

src/frontend/src/components/public/StatusChangeDropDown/index.tsx

- Introduced a bug in last commit of original UTOPIA-1038 branch, fixed it here.

[UTOPIA-1038] Fixed tab issue

---

src/frontend/src/components/public/PIAFormTabs/ppq/messages.ts

- Fix wording in PPQ final question
locally

[UTOPIA-1469] Fix wording in PPQ final question

---

.github/PULL_REQUEST_TEMPLATE.md

[UTOPIA-1476](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1476)
- Updated template to match common components repo.

UTOPIA-1476: Updated pull request template

---

src/frontend/src/components/common/Dropdown/index.tsx
src/frontend/src/components/common/InputText/InputText.tsx
src/frontend/src/components/common/Navbar/index.tsx
src/frontend/src/components/common/Radio/index.tsx
src/frontend/src/components/common/Radio/interfaces.ts
src/frontend/src/components/common/Table/views/useTableRowView.tsx
src/frontend/src/components/common/Table/views/useTableStandardView.tsx
src/frontend/src/components/common/ViewComment/index.tsx
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx
src/frontend/src/components/public/PIAFormTabs/ppq/index.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx

[UTOPIA-1186](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1186)
- Dropdown uses label prop instead of id (if available).
- NavLink uses page.label.
- Radio button now has groupLabel prop to link question with radio option.
- Added various missing labels.

UTOPIA-1186: Improved screen reader labels

---

src/backend/package-lock.json
src/backend/package.json

[UTOPIA-1442](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1442)
- Remove rimraf (BE prod dependency)

[UTOPIA-1442] - Remove rimraf (BE prod dependency)

---

src/backend/package.json

[UTOPIA-1442](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1442)
Modified npm script for removal of rimraf

UTOPIA-1442: Modify npm script

---

src/frontend/src/components/public/PIAFormTabs/intake/index.tsx

[UTOPIA-1186](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1186)
Added aria label to pia intake question

UTOPIA-1186: Added aria label to pia intake question

---

src/backend/package-lock.json
src/backend/package.json

[UTOPIA-1443](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1443) Nestjs Bundle
[UTOPIA-1453](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1453) Axios
[UTOPIA-1445](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1445) Typeorm
[UTOPIA-1444](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1444) Swagger
[UTOPIA-1454](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1454) Typescript
Had to combine multiple tickets because all the nestjs package updates were dependent on each other and typescript.
> - I have consulted with the team if introducing a …

UTOPIA-[1443,1453,1445,1444,1454] Major Dependency Updates (Backend)

---

src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/utils/autosave.ts

[UTOPIA-1460](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1460)
- seperated autosave function to its own utility file
- reorganized and refactored autosave function
- added comments to autosave util file

[UTOPIA-1460] - Separate auto save function from src\frontend\src\pages\PIAForm\index.tsx

---

src/frontend/src/pages/PIAForm/index.tsx

[UTOPIA-1294](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1294) 
* Fixed edit button to send correct variable(isSubmit:false)

[UTOPIA-1294] Interact with the Common State Machine upon all PIA interactions (Modal)

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1438](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1438)
- update vite
- @vitejs/plugin-react

[UTOPIA-1438] - Update vite (FE dev dependency)

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1440](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1440)
- Update lint-staged

[UTOPIA-1440] - Update lint-staged (FE dev dependency)

---

src/frontend/nginx.conf
src/frontend/public/snowplow.js
src/frontend/src/pages/PIAForm/index.tsx

[UTOPIA-1455](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1455)
- Modified security policy for nginx config.
- Modified snowplow call to use production url in production environment.
- Truncated pia title in snowplow call to 64 characters.

UTOPIA-1455: Snowplow production analytics

---

src/backend/src/common/utils/arraysEqual.ts
src/backend/src/common/utils/checkMatching.ts
src/backend/src/common/utils/objectComparison.ts
src/backend/src/common/validators/form-field-role.validator.ts
src/backend/src/modules/pia-intake/helper/handle-pia-updates.ts
src/backend/test/unit/common/utils/isMatching.spec.ts
src/backend/test/unit/common/utils/objectComparison.spec.ts

[UTOPIA-1490](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1490)
Autosave error occurred because json b validation in backend didn't recognize updated and stored value being equal if the values were arrays.
- Added function to check if two arrays are equal.
- Added function to check if two values are equal.
- Added tests for util functions.

UTOPIA-1490: Autosave error occurs when CPO tries to review and sign PIA

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/index.tsx
src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts

[UTOPIA-1478](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1478)
- Added setTimeout to ensure that state updates do not conflict with the current rendering cycle. 

[UTOPIA-1478] User does not see full PIA after sharing with MPO from Next Steps page

---

src/frontend/src/components/public/PIASubHeader/_piasubheader.scss
src/frontend/src/components/public/PIASubHeader/index.tsx

[UTOPIA-1327](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1327)
Only had to adjust sizing on next steps page because other pages were already fixed.

UTOPIA-1327: Status, Save and Three Dots buttons are not the same size

---

src/frontend/src/pages/LandingPage/LandingPage.tsx
src/frontend/src/pages/LandingPage/messages.ts

[UTOPIA-1316](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1316)
- created messages file to house all messaging for landing page
- imported and used newly created messages file in landing page

[UTOPIA-1316] - Project Update on DPIA Landing Page

---

src/frontend/src/utils/statusList/statuses/cpoReviewStatus.ts
src/frontend/src/utils/statusList/statuses/incompleteStatus.ts
src/frontend/src/utils/statusList/statuses/mpoReviewStatus.ts

[UTOPIA-1496](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1496)
- Removed drafter's access to ppq in incomplete.
- Limited drafter's to read only for ppq in mpo and cpo review.

UTOPIA-1496 Modifications - Drafter access to PPQ

---

src/frontend/src/pages/PPQPage/PPQPage.tsx
src/frontend/src/pages/PPQPage/messages.ts

[UTOPIA-1136](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1136)
- Added missing link on Create New page

[UTOPIA-1136] Missing link on Create New page

---

src/backend/src/migrations/1698356250344-removeNextStepsProperties.ts

[UTOPIA-1536](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1536)
- Migration drops next steps columns

UTOPIA-1536: Added migration for Next Steps changes

---

src/frontend/src/sass/_comment_sidebar.scss

[UTOPIA-1537](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1537)
- made comments scrollable

[UTOPIA-1537] - Comments no longer scrollable

---

src/frontend/src/components/public/ListViewRender/tableProperties.ts

[UTOPIA-1290](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1290)
- Last modified is now in descending order by default

UTOPIA-1290: List of PIAs is not sorted by last modified by default

---

src/frontend/src/components/public/PIAFormTabs/nextSteps/nextStepsPI/components/PIALifecycle.tsx
src/frontend/src/sass/_nextSteps.scss

[UTOPIA-1354](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1354)
- changed the nextStep CSS file to limit the max width size based on the upper div.

[UTOPIA-1354] Process Map / Infographic for DPIA

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1440](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1440)

UTOPIA-1440: Update lint-staged (FE dev dependency)

---

src/e2e/.eslintignore
src/e2e/.eslintrc.js
src/e2e/.prettierignore
src/e2e/.prettierrc
src/e2e/package-lock.json
src/e2e/package.json
src/e2e/playwright.config.ts
src/e2e/tests/example.spec.ts
src/e2e/tsconfig.eslint.json
src/e2e/tsconfig.json
src/e2e/tsconfig.node.json

[UTOPIA-1471](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1471)
- add and configure prettier and eslint

[UTOPIA-1471] - (TESTING) Set up a basic Playwright environment for testing

---

src/frontend/src/components/public/ListViewRender/index.tsx

[UTOPIA-1290](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1290)

UTOPIA-1290: Fix descending order lastModified pias

---

.github/workflows/build-deploy-app.yaml
.github/workflows/e2e-test.yaml
.github/workflows/tag-deploy-app-test.yaml

[UTOPIA-1474](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1474)
- updated checkouts to v4
- fix issue with workflow_call using the wrong input types.
- linted files

[UTOPIA-1474] - (TESTING) Integrate Playwright into our CI/CD pipeline.

---

src/e2e/package-lock.json
src/e2e/package.json

[UTOPIA-1568](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1568)
[Dependency Updates Report](https://github.com/bcgov/cirmo-dpia/issues/1772)

UTOPIA-1568: Minor/Patch Updates (E2E)

---

.github/workflows/api-npm-dep-report.yaml
.github/workflows/app-npm-dep-report.yaml
.github/workflows/e2e-npm-dep-report.yaml

[UTOPIA-1568](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1568)
- Updated names of workflows
- Updated checkout action to v4

UTOPIA-1568: Updated workflows

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1546](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1546)
Updated richtexteditor to v1.4.1 to add window resizing.

UTOPIA-1546: Updated richtexteditor to v1.4.1

---

src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx

Removed console log

---

src/backend/src/migrations/1700069709417-RichTextSecurityPI.ts
src/backend/src/modules/pia-intake/jsonb-classes/security-personal-information/access-to-personal-information.ts
src/backend/src/modules/pia-intake/jsonb-classes/security-personal-information/digital-tools-and-systems/section-storage.ts
src/backend/src/modules/pia-intake/mocks/create-pia-intake.mock.ts
src/backend/test/util/mocks/data/pia-empty-jsonb-values.mock.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/security-personal-info-interface.ts

[UTOPIA-1559](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1559)
1. Replace text editor in frontend.
2. Update jsonb.
3. Update unit test mocks.
- Use VSCode search to look for property, include files from `src/backend`, exclude files from `dist/*, *.html`.
- Add necessary ` { content: '' }`.
4. Add migration.
- Run `make api-workspace`.
- Run `npm run migration:create src/migrations/<your-migration-name>` where `<your-migration-name>` is something like `RichTextSecurityPI`.
- Add up and down function to migration and edit.
- Run `npm run migration:run`.
5. Update frontend to reference new  type.
6. Make sure tests pass in backend `npm test pia-intake`.
> - I have made …

UTOPIA-1559: Implement Rich Text Editor on Security of personal information tab

---

openshift/templates/custom-resource-definitions/sysdig-team.yaml

[UTOPIA-1571](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1571)
- Adds sysdig team config to openshift/custom-resource-definitions

UTOPIA-1571: SysDig Monitoring

---

src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx

[UTOPIA-1556](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1556)
- MPO only field now only editable to MPOs

UTOPIA-1556: Condition for MPO only field on Collection, Use and Disclosure

---

src/backend/src/migrations/1700158801488-RichTextAgreementsAndInfoBanks.ts
src/backend/src/modules/pia-intake/jsonb-classes/agreements-and-information-banks/information-sharing-agreement.ts
src/backend/src/modules/pia-intake/jsonb-classes/agreements-and-information-banks/personal-information-banks.ts
src/backend/src/modules/pia-intake/mocks/create-pia-intake.mock.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/components/InformationSharingAgreement.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/components/PersonalInformationBanks.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/helper/IAgreementsInfo-interface.ts
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/index.tsx

[UTOPIA-1561](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1561)
- Updated jsonb types in the backend and updated mocks.
- Created migration.
- Replaced text editor on the agreements and Information Bank tab.
- Ensured tests pass in the backend.

[UTOPIA-1561] Implement package for text editor on Agreements and information banks tab

---

src/backend/src/migrations/1700162931296-RichTextAccuracyCorrectionRetention.ts
src/backend/src/modules/pia-intake/jsonb-classes/accuracy-correction-and-retention/accuracy.ts
src/backend/src/modules/pia-intake/jsonb-classes/accuracy-correction-and-retention/retention.ts
src/backend/src/modules/pia-intake/mocks/create-pia-intake.mock.ts
src/backend/test/util/mocks/data/pia-empty-jsonb-values.mock.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/accuracy-retention-interface.ts
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/components/AccuracySection.tsx
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/components/PersonalInformationSection.tsx
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/index.tsx

[UTOPIA-1560](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1560)
- Replaced MDEditor with RichTextEditor
- Updated jsonb and mocks.
- Added migration.
- Updated type in frontend.

UTOPIA-1560: Implement RichTextEditor on Accuracy, correction, retention tab

---

openshift/templates/custom-resource-definitions/sysdig-team.yaml

[UTOPIA-1581](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1581)
- Add Chris McGlones' team
- Add Sylar
- Add remaining DPIA devs

UTOPIA-1581: Update sysdig-team.yaml

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1534](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1534)
- Adds highlighter style option 

UTOPIA-1534: Update richtexteditor to v1.5.1

---

src/frontend/src/utils/generateUID.ts

[UTOPIA-1543](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1543)
For future use in the collection use and disclosure steps. Each step will get a UID starting with the timestamp as a string, followed by a random number.

UTOPIA-1543: Function to generate unique identifiers

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1533](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1533)
- Adds numbered lists to rich text editor

UTOPIA-1533: Updated richtexteditor v1.6.0 numbered lists

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/public/PIAFormTabs/ppq/index.tsx

- Update richtext v1.6.1 to fix styling issue
- Fixed ppq other field (text box should only be visible when other checkbox is selected)

Update richtext 1.6.1

---

src/e2e/tests/modules/piaFill/mpoPiaFill.ts
src/frontend/src/components/public/PIAFormTabs/ppq/index.tsx

[UTOPIA-1472](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1472)
- re-enable ability to check ppq "other" button

[UTOPIA - 1472] - (TESTING) Transfer old tests to use Playwright.

---

src/frontend/src/components/public/CommentsSidebar/index.tsx

[UTOPIA-1540](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1540)
- added useEffect to determine scroll height and smoothly scroll to the bottom on new added or deleted comments

[UTOPIA-1540] - make comments scroll to the bottom automatically when a new comment is added

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1535](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1535)
- Adds font sizing options

UTOPIA-1535: Update richtexteditor v1.7.0 (font sizing)

---

src/e2e/package-lock.json
src/e2e/package.json

[UTOPIA-1567](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1567)

UTOPIA-1567: Patch/Minor Dependency Updates (E2E)

---

src/frontend/src/components/public/PIAFormTabs/ppq/index.tsx

[UTOPIA-1583](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1583)
Removed char count logic as it was causing issues and wasn't implemented correctly. We will be adding this as a feature of the RichTextEditor component anyways. For now it just says the limit is 500 characters but doesn't enforce it.

UTOPIA-1583: Fix ppq richtext

---

src/e2e/playwright.config.ts
src/e2e/tests/authorized.spec.ts
src/e2e/tests/autosave.spec.ts
src/e2e/tests/comments.spec.ts
src/e2e/tests/filter.spec.ts
src/e2e/tests/fullPia.spec.ts
src/e2e/tests/landingPage.spec.ts
src/e2e/tests/modules/piaFill/basicPiaFill.ts
src/e2e/tests/modules/piaFill/cpoPiaFill.ts
src/e2e/tests/modules/piaFill/drafterPiaFill.ts
src/e2e/tests/modules/piaFill/mpoPiaFill.ts
src/e2e/tests/search.spec.ts
src/e2e/tests/sort.spec.ts
src/e2e/tests/tooltip.spec.ts
src/e2e/tests/unauthorized.spec.ts
src/frontend/src/components/public/CommentsSidebar/index.tsx

[UTOPIA-1472](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1472)
- update serialization to use modern implementation
- added larger global timeouts
- use better locators for failing tests

[UTOPIA-1472] - (TESTING) Transfer old tests to use Playwright.

---

src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx

[UTOPIA-1609](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1609)
- Removed form element to prevent automatic submission when a button from rich text editor is clicked.

UTOPIA-1609: Prevent auto submit on standalone ppq

---

src/frontend/src/components/common/ImageMagnifier/index.tsx
src/frontend/src/components/common/Tooltip/index.tsx
src/frontend/src/components/common/Tooltip/interfaces.ts
src/frontend/src/sass/_nextSteps.scss
src/frontend/src/sass/_tooltip.scss

[UTOPIA-1541](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1541)
- fix styling for toolbar to add highlighting

[UTOPIA-1541] - Add image click to PIA lifecycle diagram to make it easier to read

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1547](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1547)
- Adds insert link option
- NOTE: Must be in read only mode to click hyperlink.

UTOPIA-1547: Updated richtexteditor v1.8.0 (insert link)

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1545](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1545)
- Adds undo action

UTOPIA-1545: Updated richtexteditor v1.9.0 (Undo action)

---

src/frontend/src/components/common/Pagination/listPageNumber.tsx

[UTOPIA-1555](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1555)
- added double arrows to jump to first and last pages
- only 10 pages show at a time and made arrows smoothly navigate through the list
- added ability to click individual page numbers using keyboard

[UTOPIA-1555] - Fix # of pages display

---

src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts

[UTOPIA-1610](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1610)
- added submitted at and status conditions to stop side tabs from showing while still drafting

[UTOPIA-1610] - New PIAs are submitted on first autosave

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1580](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1580)
- Improves newlines in rich text editor

UTOPIA-1580: Updated richtext v1.9.2 (Newlines improvements)

---

src/e2e/package-lock.json
src/e2e/package.json

[UTOPIA-1569](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1569)

UTOPIA-1569: Patch/Minor dependency updates (E2E)

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1565](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1565)
- Adds tooltips to rich text buttons
- Fixes sizing issue with icons in the rich text buttons

UTOPIA-1565: Updated richtext v1.10.1 (tooltips)

---

src/frontend/package-lock.json
src/frontend/package.json

[UTOPIA-1564](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1564)
- Adds active state to buttons so button is highlighted when active.

UTOPIA-1564: Update richtext v1.11.0 (active buttons)

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/public/PIAFormTabs/intake/printPreview/intakedetails.tsx

[UTOPIA-1557](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1557)
- Allows setContent to be undefined when readOnly is true in RichTextEditor

UTOPIA-1557: Update richtext v1.11.1 (allow undefined setContent)

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/components/AccuracySection.tsx
src/frontend/src/components/public/PIAFormTabs/accuracyRetention/components/PersonalInformationSection.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/components/InformationSharingAgreement.tsx
src/frontend/src/components/public/PIAFormTabs/agreementsAndInformationBanks/components/PersonalInformationBanks.tsx
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx
src/frontend/src/components/public/PIAFormTabs/intake/components/IntakeInitiativeDescription.tsx
src/frontend/src/components/public/PIAFormTabs/intake/components/IntakeInitiativeDetails.tsx
src/frontend/src/components/public/PIAFormTabs/intake/components/IntakeInitiativeScope.tsx
src/frontend/src/components/public/PIAFormTabs/intake/components/IntakePersonalInformation.tsx
src/frontend/src/components/public/PIAFormTabs/intake/printPreview/intakedetails.tsx
src/frontend/src/components/public/PIAFormTabs/ppq/index.tsx
src/frontend/src/components/public/PIAFormTabs/securityPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx

[UTOPIA-1563](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1563)
- Adds text only read only mode

UTOPIA-1563: Update richtext v1.12.1 (text only mode)

---

src/frontend/src/components/public/PIAFormTabs/intake/printPreview/index.tsx
src/frontend/src/components/public/PIAFormTabs/intake/printPreview/intakedetails.tsx

[UTOPIA-1584](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1584)
- Fixed styling of print preview intake form

UTOPIA-1584: Print preview intake column adjustment

---

src/frontend/src/components/common/CustomInputDate/custom_input_date.scss
src/frontend/src/components/common/CustomInputDate/index.tsx

[UTOPIA-1619](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1619)
- Increased z index for date picker

UTOPIA-1619: PPQ date picker z-index

---

src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts

[UTOPIA-1611](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1611)
- revert functionality 

[UTOPIA-1611] New PIAs are submitted on first autosave

---

src/frontend/src/App.tsx
src/frontend/src/components/common/Collapsible/index.tsx
src/frontend/src/components/common/ImageMagnifier/index.tsx
src/frontend/src/components/common/Pagination/listPageNumber.tsx
src/frontend/src/components/public/PIAListTable/TableOrdering.tsx
src/frontend/src/components/public/PIAListTable/index.tsx
src/frontend/src/utils/keyboardAccessibility.tsx

[UTOPIA-1621](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1621)
- create keyboard accessibility utility 
- wrap app component with utility
- remove redundant onKeyDowns

[UTOPIA-1621] - Enter Button is not treated as a click throughout majority of application

---

src/backend/src/migrations/1701818277807-CreateReplyTable.ts
src/backend/src/modules/comments/entities/comment.entity.ts
src/backend/src/modules/comments/entities/reply.entity.ts

[UTOPIA-696](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-696)
- Adds comment reply table

UTOPIA-696: Added comment reply table

---

src/e2e/package-lock.json
src/e2e/package.json

[UTOPIA-1633](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1633)

UTOPIA-1633: Patch/Minor Dependency Updates (E2E)

---

src/frontend/src/components/public/PIAFormTabs/review/ProgramArea/AddHideRolesToggle.tsx

[UTOPIA-1593](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1593)

[UTOPIA-1593] - (Frontend) after Clicking on "add roles", "hide roles" should have a minus symbol

---

src/frontend/src/sass/_table.scss

[UTOPIA-1566](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1566)
- added 100% table width and fixed column spacing

[UTOPIA-1566] - Clicking between ascending and descending changes column spacing

---

src/frontend/src/pages/PPQPage/PPQPage.tsx

[UTOPIA-1639](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1639)
- add notice to make new pia's inaccessible

[UTOPIA-1639] - Disable "create new" function

---

src/frontend/src/components/public/CommentsSidebar/CommentsSidebar.scss
src/frontend/src/components/public/CommentsSidebar/index.tsx
src/frontend/src/components/public/CommentsSidebar/interfaces.ts
src/frontend/src/sass/common.scss

[UTOPIA-695](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-695)
- TODO: delete reply function and add reply function

UTOPIA-695: Comment Reply UI

---

src/backend/src/modules/comments/comments.module.ts
src/backend/src/modules/comments/comments.service.ts
src/frontend/src/components/public/CommentsSidebar/CommentsSidebar.scss
src/frontend/src/components/public/CommentsSidebar/index.tsx
src/frontend/src/constant/apiRoutes.ts

[UTOPIA-534](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-534)

UTOPIA-534: Fixes to comment replies

---

src/backend/README.md

[UTOPIA-1640](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1640)

UTOPIA-1640: Update backend Readme

---

src/backend/package-lock.json
src/backend/package.json

[UTOPIA-1634](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1634)

UTOPIA-1634: Update patch/minor dependencies (Backend)

---

src/e2e/package-lock.json
src/e2e/package.json

[UTOPIA-1634](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1634)

UTOPIA-1634: Update patch/minor dependencies (E2E)

---

src/e2e/tests/comments.spec.ts
src/e2e/tests/modules/piaFill/basicPiaFill.ts
src/e2e/tests/sort.spec.ts

[UTOPIA-1586](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1586)
- Added comment test on the collection, use, and disclosure steps 
- Fixed basicPiaFill function for each of the input fields (made as a comment for previous code) 

[UTOPIA-1586] end-to-end test

---

.github/workflows/api-unit-test.yaml

Had syntax errors and actions needed updating

Update Unit Test Workflow

---

src/frontend/README.md

Added frontend readme

---

src/frontend/README.md

Add information about autosave

---

.github/dependabot.yaml

Disable dependabot

---

src/frontend/src/pages/PPQPage/PPQPage.tsx

[UTOPIA-](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-)
- update ppqpage to remove sunset message

Update ppqpage to remove sunset message
