docker-compose.local.yaml

- downgrading pg db from 14.5 to 10.21 until OpenShift supports it

downgrading pg db from 14.5 to 10.21 until OpenShift supports it

---

docker-compose.local.yaml
src/frontend/.config/.env.local
src/frontend/package.json
src/frontend/src/constant/api.ts
src/frontend/src/utils/requestUtil.ts
src/frontend/vite.config.local.ts

- Removed env to align with same base route strategy
- Added proxy support for local development where same base route strategy won't work with apps running on separate ports

[UTOPIA-351] [Frontend] removed env support to align with same base route strategy

---

src/backend/src/modules/ppq/ppq.service.ts

- Identified an issue during own testing that the proposedStartDate when passed null was printing a 1970 date on PDF
This issues came up as part of the personal testing. Verified the fix by passing null date from frontend.

[UTOPIA-273] [Backend] fix pdf output when proposedStartDate field is null

---

src/backend/src/migrations/1666983517409-ppq-form-update-other-factors-fields.ts
src/backend/src/modules/ppq/constants/ppq-other-factors.constant.ts
src/backend/src/modules/ppq/dto/ppq-post.dto.ts
src/backend/src/modules/ppq/entities/ppq.entity.ts
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx
src/frontend/src/ts/interfaces/ppq-form.interface.ts

- Migration removing fields - `has_high_volumes_personal_information`, `has_data_linking `
- Removes references to the above fields
Verified that the app is working as expected after the migration is run

[UTOPIA-381] Added migration and changes to remove fields not required anymore

---

src/frontend/src/components/common/ScrollToTop/index.ts
src/frontend/src/main.tsx

- Creates ScrollToTop component to handle scrolling to the top of the page on re-route
Clicked 'Next' on PPQ form page and confirmed the page scrolls to top on re-route.

UTOPIA-400: View bottom of screen instead of top

---

src/frontend/src/components/public/PIAIntakeResults/index.tsx

- fix pia intake result page download btn css

[UTOPIA-438]update pia intake results page download btn css

---

src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/hooks/usePIALookup.ts
src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx
src/frontend/src/utils/file-download.util.ts
src/frontend/src/utils/getAccessToken.ts
src/frontend/src/utils/http-request.util.ts

- Logout is behind auth now
- Refactor to add auth by default to all endpoints except keycloakLogin and callback methods
Tested the complete flow

[UTOPIA-579] [Frontend] All endpoints including Logout behind auth except Login and callback

---

src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/components/common/Modal/_modal.scss
src/frontend/src/components/common/Modal/index.tsx
src/frontend/src/components/common/Modal/interfaces.ts
src/frontend/src/components/common/Unauthorized/index.tsx
src/frontend/src/pages/PIADetailPage/index.tsx
src/frontend/src/pages/PIADetailPage/messages.ts
src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/pages/PIAIntakeForm/messages.ts
src/frontend/src/sass/_form.scss

- Implements save modal for PIA intake
- Tweaks existing modal component to allow for reversed button order as the 'sign out' modal's buttons are opposite of iteration 4 modals
Visual assertion of modals based on which button triggers the modal.

UTOPIA-608: [Front End] Create UI Save before submitting modal

---

src/frontend/src/constant/constant.ts
src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/sass/index.scss

- Adds alert for when user tries to refresh or navigate away from unsaved/unsubmitted form
- Adds status to http request body for pia intake
The alertUserLeave function uses `e.returnValue`, which has been deprecated for 9+ years. The reason for this usage is to support Chrome which only behaves as expected when using this value.
Below are a couple of references on this topic.
- https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue
- https://contest-server.cs.uchicago.edu/ref/JavaScript/developer.mozilla.org/en-US/docs/Web/API/Event/returnValue.html

UTOPIA-607: [Front End] Handle page refresh

---

src/frontend/src/pages/PIAIntakeForm/index.tsx

- Fixes the lack of warning for users leaving the PIA Intake page (edit or new) using the 'Back' button at the bottom of the PIA Intake form
Clicked the 'Back' button on the PIA Intake form for both new and existing PIAs

UTOPIA-666: [Frontend] Fix PIA Leave Page Warning

---

src/frontend/src/sass/_table.scss

- Makes the title column of the PIA list a fixed width of `50ch`
A more responsive solution may need to be explored in future iterations.
Visual assertion of changes.

UTOPIA-703: Text elements move and resizing issue

---

src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

- fix filter query for ministry query. only allow the user to query there own ministry pia

[UTOPIA-366]update filter query to eliminate unauthorized access pia

---

src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/src/modules/ppq/ppq.service.ts
src/backend/src/modules/ppq/templates/ppq-result.pug

- partial saved data does not break PIA-intake pdf download
- removed N/A from all PDF - not the right terminology
Generating PDF from the app

[UTOPIA-735] PDF breaking fix for partial save + pdf should not contain 'N/A'

---

src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/pages/PIAIntakeForm/messages.ts

- Failure popup on auto-save fail
Go offline and makes changes to the app; Come back online to reflect auto-save happens; and then go back offline and make change to see the popup appears again

[UTOPIA-750] [Frontend] Failure popup on auto-save fail

---

src/backend/src/common/validators/date-string.validator.ts
src/backend/src/migrations/1675472710074-ppq-propose-date-timestamp-to-date-string.ts
src/backend/src/modules/ppq/dto/ppq-post.dto.ts
src/backend/src/modules/ppq/entities/ppq.entity.ts
src/backend/src/modules/ppq/ppq.service.ts
src/backend/test/unit/common/validators/date-string.validator.spec.ts
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx
src/frontend/src/types/interfaces/ppq-form.interface.ts

Currently, we are storing our PPQ with proposed start date as Timestamp in the database. This is problematic. Changing it to store date only in YYYY/MM/DD format.
[*This PR updates existing data via migration; May require local API container to be restarted.*]
- Updated `proposedStartDate` in PPQ to date string [YYYY/MM/DD]
- Migration to convert existing timestamp to dateString
- Custom Validator with relevant Test cases
- Corresponding Frontend changes to send date string instead of timestamp
Tested by creating PPQs with and without proposedStartDate. Also tested via Swagger and the test cases written in the code.

[UTOPIA-528] Updated `proposedStartDate` in PPQ to date string instead of Timestamp

---

src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts
src/frontend/src/pages/PIADetailPage/index.tsx
src/frontend/src/pages/PIAIntakeForm/index.tsx
src/frontend/src/types/interfaces/pia-intake.interface.ts

- Display the submitteAt in pia intake detail page with the correct value, previous we use createdAt, now will use the new submittedAt column to show the correct date

[UTOPIA-777] update submittedat in frontend end

---

src/backend/src/migrations/1678142798474-piaIntakeAddColumnsNextStepFlags.ts
src/backend/src/modules/pia-intake/dto/create-pia-intake.dto.ts
src/backend/src/modules/pia-intake/entities/pia-intake.entity.ts
src/backend/src/modules/pia-intake/mocks/create-pia-intake.mock.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts

- [PIA Intake table] New column added - is_next_steps_seen_for_delegated_flow
- [PIA Intake table] New column added - is_next_steps_seen_for_non_delegated_flow
- Migration added
- DTO updated
- Tests updated
via Swagger

[UTOPIA-848] Add new nextSteps flags to pia-intake

---

src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/messages.ts

- External links now include an icon
- External links now open in a new tab
- Visual assessment of style changes
- Clicked links to assert that behaviour was as expected

UTOPIA-886: Add External link behaviour to all “more info” links on Storing PI tab

---

src/frontend/src/components/common/Navbar/_navbar.scss
src/frontend/src/components/public/PIAListTable/index.tsx
src/frontend/src/pages/PIAForm/index.tsx
src/frontend/src/sass/_default.scss
src/frontend/src/sass/_sideNav.scss

- [UTOPIA-892] BugFix: Border under Drafter name in smaller screens
- [UTOPIA-961] Spacing between sidebar and main container
From 400px to 3000px - all works!

[UTOPIA-961] Spacing between Sidenav and main container + Border bottom drafter fix

---

src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/components/public/PIASubHeader/interfaces.ts
src/frontend/src/pages/PIAForm/index.tsx

- when user create new pia intake, first auto save will redirect url so when user refresh page the content will dispaly
- save button in ... icon will act as save and quit, when user click save button will save and come to view mode

[UTOPIA-882]change save btn to save and quit, first autosave redirect url for new pia

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/index.tsx
src/frontend/src/pages/PIAForm/index.tsx

- BUGFIX: App goes to a continuous loading loop, if the user submits Intake before auto-submit kicks in

[UTOPIA-996] fix: user submits intake before autosave

---

src/frontend/src/sass/_sideNav.scss

- Gives side nav list items a small padding to allow for the focus outline to show
- Specifies outline styling on side nav items
Tab through side nav items and visually assert focus outline existence as per the figma designs.

UTOPIA-1048: Keyboard navigation for sidebar works but visibility of highlighting the lists is minimal

---

src/frontend/src/utils/status.ts

- MPO can submit, via the status dropdown, for CPO Review.
As an MPO role only, used the status dropdown to submit for CPO Review. Could not reverse using the dropdown, as expected.

UTOPIA-1103: MPO does not have CPO Review option in status dropdown list

---

src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/index.tsx
src/frontend/src/components/public/PIAFormTabs/storingPersonalInformation/messages.ts

- Remove unnecessary MPO role checks on fields within the storingPersonalInformation tab
Removed all roles from myself. Entered data into the fields in question. Worked as expected.

UTOPIA-1104: Multiple text fields accessible to only MPOs in Storing PI tab

---

src/frontend/src/components/public/PIAIntakeFilter/index.tsx

- UI for status filter renders correctly when user is a drafter-only role
Checked dropdown UI size for each available role.

UTOPIA-1015: "Filter By Status" field is cut off for Drafter role

---

src/frontend/src/pages/PIAForm/BannerStatus/index.tsx

- now the banner will display only the state machine will return a value otherwise it will hidde

[UTOPIA-1002] fix the banner display for cpo review status

---

src/frontend/src/pages/LandingPage/LandingPage.scss
src/frontend/src/pages/LandingPage/LandingPage.tsx

- After discuss with the Designer, the new fix will make sure the background picture only show in xxl screen, otherwise display picture above the text

[UTOPIA-991] make background picture only display on xxl size screen

---

src/backend/src/app.module.ts
src/backend/src/common/swagger.ts
src/backend/src/migrations/1686005634115-invites-entity.ts
src/backend/src/modules/comments/comments.service.ts
src/backend/src/modules/invites/dto/generate-invite.dto.ts
src/backend/src/modules/invites/entities/invite.entity.ts
src/backend/src/modules/invites/invites.controller.ts
src/backend/src/modules/invites/invites.module.ts
src/backend/src/modules/invites/invites.service.ts
src/backend/src/modules/invites/ro/get-invite.ro.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/comments/comments.service.spec.ts
src/backend/test/unit/invites/invites.controller.spec.ts
src/backend/test/unit/invites/invites.service.spec.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts
src/backend/test/util/mocks/data/invites.mock.ts
src/backend/test/util/mocks/services/comments.service.mock.ts
src/backend/test/util/mocks/services/invites.service.mock.ts
src/backend/test/util/mocks/services/pia-intake.service.mock.ts

- moved validatePiaAccess method to PiaService
- Generate Invite Code endpoint implementation
- Migration to create `invite` table and constraints
- Relevant test cases
You can use swagger to test this PR
1. See if you're able to generate the invite code using the new /invite endpoint
2. Validate that the code is not regenerated, if already done one
You can also comment or validate if you swagger docs is intuitive enough to understand.

[UTOPIA-1170] Generate Invite Code endpoint implementation with migration and test cases

---

src/backend/src/migrations/1686005634115-invites-entity.ts
src/backend/src/modules/invites/entities/invite.entity.ts
src/backend/src/modules/invites/invites.service.ts
src/backend/test/unit/invites/invites.service.spec.ts
src/backend/test/util/mocks/data/invites.mock.ts

- Apparently due to DB restrictions, moving the UUID generator to API
- Build in module 
Swagger

[UTOPIA-1170] [Build fix attempt #2] moved UUID generator from Db to API

---

src/frontend/package-lock.json
src/frontend/package.json

- Upgrades vite@3.2.5 => vite@3.2.7
Rebuilt and ran the application with no issues.

UTOPIA-1224: Vite Server options (server.fs.deny) can be bypassed using a double forward-slash

---

src/frontend/src/components/common/Modal/_modal.scss
src/frontend/src/components/common/Modal/index.tsx
src/frontend/src/sass/_statusBlock.scss
src/frontend/src/sass/_variables.scss
src/frontend/src/utils/status.ts

- Modal styling now more accurately matches designs
- Adds 'defaultFinalReviewModal' to the modal property of the Final Review status
- Status colours now more accurate to designs
- Status titles no longer all caps
- Adds Final Review status
- Updates modal content for moving *from* Final Review
Used pgAdmin to manually change status of PIAs to Final Review then, using the dropdown, selected different statuses to check modal content. For the Final Review submission modal, I simply added the Final Review to the CPO's privileges in the CPO Review status and selected it in the dropdown. I removed it after the test due to the inability to __actually__ submit to that status at this point in time.
**If new dependencies are being introduced to …

UTOPIA-1176 & 1156: (frontend) update modal, statuses, and transitions

---

src/backend/src/modules/pia-intake/enums/pia-intake-status.enum.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts

- Delete review section when moving from FINAL_REVIEW to Incomplete/Edit in Progress

[UTOPIA-1155] delete review on status revert

---

src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts
src/frontend/src/pages/PIAForm/index.tsx

- hide review tab if change status from final review to incomplete/edit in progres
- if user change status in review tab, redirect to intake tab as the review tab will disappear after status change

[UTOPIA-1238] hide review tab after change status from final_review to incomplete/edit_in_progress

---

src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/pages/PIAForm/index.tsx

- update button text to finish review from final review

[Utopia 1253] update btn text

---

src/frontend/src/pages/PIAForm/index.tsx

- Add setFormReadOnly(true) for all non-editable statuses
Attempted URL manipulation within all non-edit statuses

UTOPIA-1154: Disallow URL navigation to Edit mode when in Signature mode

---

src/frontend/src/components/public/PIANavButton/index.tsx

- Drafters without a role will no longer see a next button on the next steps tab
Changed roles and visually asserted the presence (or lack of) 'Next' button on Next Steps tab

UTOPIA-1281: Drafters can access Review Page in MPO review status

---

src/frontend/src/components/public/PIAFormTabs/review/index.tsx
src/frontend/src/components/public/PIAFormTabs/review/viewReviewSection.tsx
src/frontend/src/utils/status.ts

- Checks for COMPLETE status as well now for rendering full Program Area reviews
- Removes Program Area 'Edit review' button when in COMPLETE status
Visually checked the UI for Program Area reviews when a PIA is in COMPLETE status

UTOPIA-1330: Program area reviews not showing in Complete status

---

src/frontend/src/components/public/CommentsSidebar/index.tsx

[UTOPIA-1208](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1208) Restrict Commenting on Completed PIAs
- Removed ability to delete comments or access comment options if comments are disabled (from statusList).
Visually, comment options icon is gone in Completed status.

[UTOPIA-1328] Removed delete comments btn in Complete status

---

.github/workflows/app-e2e.yaml
.github/workflows/build-deploy-app.yaml
.github/workflows/tag-deploy-app-test.yaml
src/frontend/package-lock.json
src/frontend/package.json
src/frontend/test/features/pageobjects/login.page.js

- Update passwords for individual IDIR - DOND, DORGALE, ANDYA

UTOPIA-1349 Update passwords for individual IDIR

---

src/backend/src/common/interfaces/form-field.interface.ts
src/backend/src/modules/pia-intake/helper/update-review-submission-fields.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/cpo-review.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/index.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/mpo-review.ts
src/backend/src/modules/pia-intake/jsonb-classes/review/program-area-review.ts
src/backend/src/modules/pia-intake/pia-intake.service.ts
src/backend/test/unit/pia-intake/helpers/update-review-submission-fields.spec.ts
src/backend/test/unit/pia-intake/jsonb-classes/review/index.spec.ts
src/backend/test/unit/pia-intake/jsonb-classes/review/program-area-review.spec.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts
src/backend/test/util/mocks/data/pia-review.mock.ts

- Added CPO Review columns
- Update CPO review system generated submission fields
- Updated Program Area reviews: One users cannot delete other users review: fix
- Appropriate tests
by adding suitable test cases; and by locally getting UTOPIA-1178

[UTOPIA-1177] added CPO review columns + deleted reviews by other user fix + tests

---

src/frontend/src/utils/status.ts

- MPO & CPO INCOMPLETE submit button visible

UTOPIA-1387: Not able to submit a PIA while creation

---

src/frontend/src/constant/constant.ts

- reordered constants list of ministry names to be in alphabetical order 

[UTOPIA-966] Alphabetical Ministry Names in Drop Down List

---

src/frontend/src/components/public/PIAFormTabs/review/ProgamArea/displayProgramArea.tsx

- [UTOPIA-1395](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1395)
- Fixed ambiguity in the logic that determines whether to display the view or edit section in each section
- Changed the function name: `allowUserReviewProgramArea` -> `viewUserReviewProgramArea` 
| viewUserReviewProgramArea | isAcknowledged | Section |
|---------------------------|----------------|---------|
| false                     | false          | edit    |
| false                     | true           | view    |
| true                      | false          | view    |
| true                      | true           | view    |

[UTOPIA-1395] Selected program area roles not visible when partially signed in Final Review

---

src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/components/common/Unauthorized/index.tsx
src/frontend/src/pages/LandingPage/LandingPage.tsx
src/frontend/src/pages/PIAActiveListPage/index.tsx
src/frontend/src/utils/auth.ts

[UTOPIA-1429](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1429)
- Made reusable login function.
- Added post login redirect url local storage varaible.
- Added fresh login state local storage variable.
- Redirects on pia list page if fresh login.
Last page on logout is saved as redirect for next login.
Invite link is properly opened after successful login.

[UTOPIA-1429] Access link redirects to PIA list

---

src/frontend/src/pages/PIAForm/index.tsx

[UTOPIA-980](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-980)
- Removed code that was redirecting to intake page.

[UTOPIA-980] Clicking “Edit” from View, user sees Edit mode of PIA intake instead of tab they are on

---

src/frontend/src/components/public/PIASubHeader/index.tsx

[UTOPIA-1390](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1390)
- Removes Save button.
- Edit/Save button doesnt show on NextSteps tab.

[UTOPIA-1390] Remove Save button

---

src/backend/package-lock.json
src/backend/package.json

[UTOPIA-1446](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1446)
Updated to `21.1.2` instead of `22.0.3` because of `nest-keycloak-connect` peer dependency requirements, but this version resolves Open redirect vulnerability.

UTOPIA-1446: Updated keycloak-connect to 21.1.2

---

src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/_collectionUseAndDisclosure.scss
src/frontend/src/components/public/PIAFormTabs/collectionUseAndDisclosure/index.tsx
src/frontend/src/sass/common.scss

[UTOPIA-866](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-866)
- Added separate CSS file for disabled editor to change the background color

[UTOPIA-866] Match disabled text field UI for MPO use only text area

---

src/frontend/src/components/public/PIAFormTabs/Next_Steps/nextStepsPI.tsx
src/frontend/src/components/public/PIASideNav/pia-form-sideNav-pages.ts

[UTOPIA-1478](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1478)
- Changes state when the "Share MPO" button is clicked to make it visible on the tab.
- Simplified the condition in the showPostIntakeTabs variable to improve readability.
- Added comments

[UTOPIA-1478] User does not see full PIA after sharing with MPO from Next Steps page

---

src/frontend/src/utils/statusList/statuses/editInProgressStatus.ts
src/frontend/src/utils/statusList/statuses/incompleteStatus.ts
src/frontend/src/utils/statusList/statuses/mpoReviewStatus.ts

[UTOPIA-1236](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1236)
- Remove the privilege for CPO users to change a CPO Review Status change dropdown in the "Incomplete," "Edit in progress," and "MPO review" statuses

[UTOPIA-1236]CPO should not be able to skip MPO review

---

src/backend/src/migrations/1700244977702-RichTextPPQ.ts
src/backend/src/modules/pia-intake/jsonb-classes/ppq/index.ts
src/backend/src/modules/pia-intake/mocks/create-pia-intake.mock.ts
src/backend/test/unit/pia-intake/pia-intake.service.spec.ts
src/backend/test/util/mocks/data/pia-intake.mock.ts
src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/public/PIAFormTabs/ppq/index.tsx
src/frontend/src/components/public/PIAFormTabs/ppq/interfaces.ts
src/frontend/src/pages/PPQFormPage/PPQFormPage.tsx

[UTOPIA-1583](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1583)
- Updated jsonb types in the backend and updated mocks.
- Created migration.
- Replaced text editor on PPQ tab.
- Ensured tests pass in the backend.
- Added state change handler function for the text editor.
- Added character limit for "pidInitiativeSummary" text editor but should be fixed more for cursor issue(the cursor moves to the beginning when the character limit of 500 is reached)
> - My changes generate …

[UTOPIA-1583] Implement package for text editor on PIA Pathways Questionnaire

---

src/frontend/src/components/common/Header/Header.tsx
src/frontend/src/components/common/Modal/index.tsx
src/frontend/src/components/public/PIASubHeader/index.tsx
src/frontend/src/pages/PIAForm/index.tsx

[UTOPIA-1594](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1594)
- Move Modals to parent scopes

[UTOPIA-1594] - (frontend) Trying to delete a comment Modal pop up does not fully darken background

---

src/backend/src/migrations/1701983062936-FixNewIntakeColumn.ts

[UTOPIA-1539](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-1539)
- Previous migration for adding reply table seemed to remove the new_intake property (Happens when generating a migration before pulling main when main has another migration that has been run on the database but is not reflected in the current branches code).
- Added new_intake property to existing records.

UTOPIA-1539: Fix migration

---

src/backend/src/modules/comments/comments.controller.ts
src/backend/src/modules/comments/comments.service.ts
src/backend/src/modules/comments/dto/create-reply.dto.ts
src/backend/src/modules/comments/ro/get-comment.ro.ts
src/backend/test/unit/comments/comments.controller.spec.ts
src/backend/test/unit/comments/comments.service.spec.ts
src/backend/test/util/mocks/data/comments.mock.ts

[UTOPIA-697](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-697)
- Added createReply method for POST /comments/reply
- Added removeReply method for DELETE /comments/reply/:id

UTOPIA-697: Comment Reply Endpoints
